services:
    _defaults:
        autowire: true

    OxidEsales\EshopCommunity\Internal\Setup\ShopConfiguration\ShopConfigurationUpdaterInterface:
        class: OxidEsales\EshopCommunity\Internal\Setup\ShopConfiguration\ShopConfigurationUpdater
