[{$order->oxorder__oxbillcompany->getRawValue()}]
[{$order->oxorder__oxbillsal->value|oxmultilangsal}] [{$order->oxorder__oxbillfname->getRawValue()}] [{$order->oxorder__oxbilllname->getRawValue()}]
[{$order->oxorder__oxbilladdinfo->getRawValue()}]
[{$order->oxorder__oxbillstreet->getRawValue()}] [{$order->oxorder__oxbillstreetnr->value}]
[{$order->oxorder__oxbillstateid->value}]
[{$order->oxorder__oxbillzip->value}] [{$order->oxorder__oxbillcity->getRawValue()}]
[{$order->oxorder__oxbillcountry->getRawValue()}]
[{if $order->oxorder__oxbillustid->value}][{oxmultilang ident="VAT_ID_NUMBER" suffix="COLON"}] [{$order->oxorder__oxbillustid->value}][{/if}]
[{oxmultilang ident="PHONE" suffix="COLON"}] [{$order->oxorder__oxbillfon->value}]
