<?php
/**
 * This file is part of OXID eShop Community Edition.
 *
 * OXID eShop Community Edition is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * OXID eShop Community Edition is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with OXID eShop Community Edition.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @link      http://www.oxid-esales.com
 * @copyright (C) OXID eSales AG 2003-2016
 * @version   OXID eShop CE
 */

namespace OxidEsales\Eshop\Core;

/**
 * @inheritdoc
 */
class ClassMap extends \OxidEsales\Eshop\Core\Edition\ClassMap
{
    /**
     * @inheritdoc
     */
    public function getOverridableMap()
    {
        return [
            'oxdbmetadatahandler' => '\OxidEsales\Eshop\Core\DbMetaDataHandler',
            'oxApplicationServer' => '\OxidEsales\Eshop\Core\ApplicationServer',
            'oxCcValidator' => '\OxidEsales\Eshop\Core\CreditCardValidator',
            'language' => '\OxidEsales\Eshop\Application\Controller\Admin\LanguageController',
            'module' => '\OxidEsales\Eshop\Application\Controller\Admin\ModuleController',
            'theme' => '\OxidEsales\Eshop\Application\Controller\Admin\ThemeController',
            'oxcompanyvatinchecker' => '\OxidEsales\Eshop\Core\CompanyVatInChecker',
            'oxcounter' => '\OxidEsales\Eshop\Core\Counter',
            'oxdebuginfo' => '\OxidEsales\Eshop\Core\DebugInfo',
            'oxdecryptor' => '\OxidEsales\Eshop\Core\Decryptor',

            'oxemail' => '\OxidEsales\Eshop\Core\Email',
            'oxencryptor' => '\OxidEsales\Eshop\Core\Encryptor',
            'oxfilecache' => '\OxidEsales\Eshop\Core\FileCache',
            'oxhasher' => '\OxidEsales\Eshop\Core\Hasher',
            'oxheader' => '\OxidEsales\Eshop\Core\Header',
            'oxinputvalidator' => '\OxidEsales\Eshop\Core\InputValidator',
            'oxmodulechainsgenerator' => '\OxidEsales\Eshop\Core\ModuleChainsGenerator',
            'oxmoduleinstaller' => '\OxidEsales\Eshop\Core\ModuleInstaller',
            'oxmodulemetadataagainstshopvalidator' => '\OxidEsales\Eshop\Core\ModuleMetadataAgainstShopValidator',
            'oxmodulevalidatorfactory' => '\OxidEsales\Eshop\Core\ModuleValidatorFactory',
            'oxmodulevariableslocator' => '\OxidEsales\Eshop\Core\ModuleVariablesLocator',
            'oxnojsvalidator' => '\OxidEsales\Eshop\Core\NoJsValidator',
            'oxonlinecaller' => '\OxidEsales\Eshop\Core\OnlineCaller',
            'oxonlinelicensecheckcaller' => '\OxidEsales\Eshop\Core\OnlineLicenseCheckCaller',
            'oxonlinelicensecheckresponse' => '\OxidEsales\Eshop\Core\OnlineLicenseCheckResponse',
            'oxpasswordhasher' => '\OxidEsales\Eshop\Core\PasswordHasher',
            'oxpasswordsaltgenerator' => '\OxidEsales\Eshop\Core\PasswordSaltGenerator',
            'oxpdf' => '\OxidEsales\Eshop\Core\Pdf',
            'oxpicturehandler' => '\OxidEsales\Eshop\Core\PictureHandler',

            'oxseodecoder' => '\OxidEsales\Eshop\Core\SeoDecoder',
            'oxsepabicvalidator' => '\OxidEsales\Eshop\Core\SepaBICValidator',
            'oxsepaibanvalidator' => '\OxidEsales\Eshop\Core\SepaIBANValidator',
            'oxsepavalidator' => '\OxidEsales\Eshop\Core\SepaValidator',
            'oxserverprocessor' => '\OxidEsales\Eshop\Core\ServerProcessor',
            'oxsha512hasher' => '\OxidEsales\Eshop\Core\Sha512Hasher',
            'oxstrregular' => '\OxidEsales\Eshop\Core\StrRegular',
            'oxsubshopspecificfilecache' => '\OxidEsales\Eshop\Core\SubShopSpecificFileCache',
            'oxsystemeventhandler' => '\OxidEsales\Eshop\Core\SystemEventHandler',
            'oxtableviewnamegenerator' => '\OxidEsales\Eshop\Core\TableViewNameGenerator',
            'oxuniversallyuniqueidgenerator' => '\OxidEsales\Eshop\Core\UniversallyUniqueIdGenerator',
            'oxusercounter' => '\OxidEsales\Eshop\Core\UserCounter',
            'oxutilscount' => '\OxidEsales\Eshop\Core\UtilsCount',
            'oxutilsfile' => '\OxidEsales\Eshop\Core\UtilsFile',
            'oxutilsstring' => '\OxidEsales\Eshop\Core\UtilsString',
            'oxutilsurl' => '\OxidEsales\Eshop\Core\UtilsUrl',
            'oxutilsview' => '\OxidEsales\Eshop\Core\UtilsView',
            'oxutilsxml' => '\OxidEsales\Eshop\Core\UtilsXml',
            'oxviewconfig' => '\OxidEsales\Eshop\Core\ViewConfig',
            'oxwidgetcontrol' => '\OxidEsales\Eshop\Core\WidgetControl',
            'emos' => 'OxidEsales\Eshop\Core\Smarty\Plugin\Emos',
            'emos_item' => 'OxidEsales\Eshop\Core\Smarty\Plugin\EmosItem',
            'oxemosadapter' => 'OxidEsales\Eshop\Core\Smarty\Plugin\EmosAdapter',

            'manufacturerlist' => '\OxidEsales\Eshop\Application\Controller\ManufacturerListController',
            'review' => '\OxidEsales\Eshop\Application\Controller\ReviewController',
            'vendorlist' => '\OxidEsales\Eshop\Application\Controller\VendorListController',
            'actions' => '\OxidEsales\Eshop\Application\Controller\Admin\ActionsController',

            'oxwactions' => '\OxidEsales\Eshop\Application\Component\Widget\Actions',
            'oxwbetanote' => '\OxidEsales\Eshop\Application\Component\Widget\BetaNote',
            'oxwcategorytree' => '\OxidEsales\Eshop\Application\Component\Widget\CategoryTree',
            'oxwinformation' => '\OxidEsales\Eshop\Application\Component\Widget\Information',
            'oxwrating' => '\OxidEsales\Eshop\Application\Component\Widget\Rating',
            'oxwservicemenu' => '\OxidEsales\Eshop\Application\Component\Widget\ServiceMenu',
            'oxwarticlebox' => '\OxidEsales\Eshop\Application\Component\Widget\ArticleBox', #
            'oxwcookienote' => '\OxidEsales\Eshop\Application\Component\Widget\CookieNote',
            'oxwlanguagelist' => '\OxidEsales\Eshop\Application\Component\Widget\LanguageList',
            'oxwrecommendation' => '\OxidEsales\Eshop\Application\Component\Widget\Recommendation',
            'oxwarticledetails' => '\OxidEsales\Eshop\Application\Component\Widget\ArticleDetails',
            'oxwcurrencylist' => '\OxidEsales\Eshop\Application\Component\Widget\CurrencyList',
            'oxwmanufacturerlist' => '\OxidEsales\Eshop\Application\Component\Widget\ManufacturerList',
            'oxwreview' => '\OxidEsales\Eshop\Application\Component\Widget\Review',
            'oxwvendorlist' => '\OxidEsales\Eshop\Application\Component\Widget\VendorList',
            'oxwidget' => '\OxidEsales\Eshop\Application\Component\Widget\Widget',
            'oxwminibasket' => '\OxidEsales\Eshop\Application\Component\Widget\MiniBasket',
            'oxwservicelist' => '\OxidEsales\Eshop\Application\Component\Widget\ServiceList',

            'oxcmp_categories' => '\OxidEsales\Eshop\Application\Component\CategoriesComponent',
            'oxcmp_lang' => '\OxidEsales\Eshop\Application\Component\LanguageComponent',
            'oxcmp_shop' => '\OxidEsales\Eshop\Application\Component\ShopComponent',
            'oxcmp_utils' => '\OxidEsales\Eshop\Application\Component\UtilsComponent',
            'oxcmp_basket' => '\OxidEsales\Eshop\Application\Component\BasketComponent',
            'oxcmp_cur' => '\OxidEsales\Eshop\Application\Component\CurrencyComponent',
            // @deprecated since v.5.3.0 (2016-06-17); The Admin Menu: Customer Info -> News feature will be moved to a module in v6.0.0
            'oxcmp_news' => '\OxidEsales\Eshop\Application\Component\NewsComponent',
            // END deprecated
            'oxcmp_user' => '\OxidEsales\Eshop\Application\Component\UserComponent',
            'oxlocator' => '\OxidEsales\Eshop\Application\Component\Locator',

            'account_user' => '\OxidEsales\Eshop\Application\Controller\AccountUserController',
            'account_wishlist' => '\OxidEsales\Eshop\Application\Controller\AccountWishlistController',

            'vendor_main' => 'OxidEsales\Eshop\Application\Controller\Admin\VendorMain',
            'vendor_main_ajax' => 'OxidEsales\Eshop\Application\Controller\Admin\VendorMainAjax',
            'vendor_seo' => 'OxidEsales\Eshop\Application\Controller\Admin\VendorSeo',
            'voucherserie' => 'OxidEsales\Eshop\Application\Controller\Admin\VoucherSerieController',
            'voucherserie_export' => 'OxidEsales\Eshop\Application\Controller\Admin\VoucherSerieExport',
            'voucherserie_generate' => 'OxidEsales\Eshop\Application\Controller\Admin\VoucherSerieGenerate',
            'voucherserie_groups' => 'OxidEsales\Eshop\Application\Controller\Admin\VoucherSerieGroups',
            'voucherserie_groups_ajax' => 'OxidEsales\Eshop\Application\Controller\Admin\VoucherSerieGroupsAjax',
            'voucherserie_list' => 'OxidEsales\Eshop\Application\Controller\Admin\VoucherSerieList',
            'voucherserie_main' => 'OxidEsales\Eshop\Application\Controller\Admin\VoucherSerieMain',
            'wrapping_list' => 'OxidEsales\Eshop\Application\Controller\Admin\WrappingList',
            'wrapping_main' => 'OxidEsales\Eshop\Application\Controller\Admin\WrappingMain',
            'dynscreen' => 'OxidEsales\Eshop\Application\Controller\Admin\DynamicScreenController',
            'dynscreen_list' => 'OxidEsales\Eshop\Application\Controller\Admin\DynamicScreenList',
            'dynscreen_local' => 'OxidEsales\Eshop\Application\Controller\Admin\DynamicScreenLocal',
            'genexport' => 'OxidEsales\Eshop\Application\Controller\Admin\GenericExport',
            'genexport_do' => 'OxidEsales\Eshop\Application\Controller\Admin\GenericExportDo',
            'genexport_main' => 'OxidEsales\Eshop\Application\Controller\Admin\GenericExportMain',
            'genimport' => 'OxidEsales\Eshop\Application\Controller\Admin\GenericImport',
            'language_list' => 'OxidEsales\Eshop\Application\Controller\Admin\LanguageList',
            'language_main' => 'OxidEsales\Eshop\Application\Controller\Admin\LanguageMain',
            'list_review' => 'OxidEsales\Eshop\Application\Controller\Admin\ListReview',
            'list_user' => 'OxidEsales\Eshop\Application\Controller\Admin\ListUser',
            'login' => 'OxidEsales\Eshop\Application\Controller\Admin\LoginController',
            'manufacturer' => 'OxidEsales\Eshop\Application\Controller\Admin\ManufacturerController',
            'manufacturer_list' => 'OxidEsales\Eshop\Application\Controller\Admin\ManufacturerList',
            'manufacturer_main' => 'OxidEsales\Eshop\Application\Controller\Admin\ManufacturerMain',
            'manufacturer_main_ajax' => 'OxidEsales\Eshop\Application\Controller\Admin\ManufacturerMainAjax',
            'manufacturer_seo' => 'OxidEsales\Eshop\Application\Controller\Admin\ManufacturerSeo',
            'module_config' => 'OxidEsales\Eshop\Application\Controller\Admin\ModuleConfiguration',
            'module_list' => 'OxidEsales\Eshop\Application\Controller\Admin\ModuleList',
            'module_main' => 'OxidEsales\Eshop\Application\Controller\Admin\ModuleMain',
            'module_sortlist' => 'OxidEsales\Eshop\Application\Controller\Admin\ModuleSortList',
            'navigation' => 'OxidEsales\Eshop\Application\Controller\Admin\NavigationController',
            'news_list' => 'OxidEsales\Eshop\Application\Controller\Admin\NewsList',
            // @deprecated since v.5.3.0 (2016-06-17); The Admin Menu: Customer Info -> News feature will be moved to a module in v6.0.0
            'news_main'      => 'OxidEsales\Eshop\Application\Controller\Admin\NewsMain',
            'news_main_ajax' => 'OxidEsales\Eshop\Application\Controller\Admin\NewsMainAjax',
            'news_text'      => 'OxidEsales\Eshop\Application\Controller\Admin\NewsText',
            // END deprecated
            'newsletter_list' => 'OxidEsales\Eshop\Application\Controller\Admin\NewsletterList',
            'newsletter_main' => 'OxidEsales\Eshop\Application\Controller\Admin\NewsletterMain',
            'newsletter_plain' => 'OxidEsales\Eshop\Application\Controller\Admin\NewsletterPlain',
            'newsletter_preview' => 'OxidEsales\Eshop\Application\Controller\Admin\NewsletterPreview',
            'newsletter_selection' => 'OxidEsales\Eshop\Application\Controller\Admin\NewsletterSelection',
            'newsletter_selection_ajax' => 'OxidEsales\Eshop\Application\Controller\Admin\NewsletterSelectionAjax',
            'newsletter_send' => 'OxidEsales\Eshop\Application\Controller\Admin\NewsletterSend',
            'order_address' => 'OxidEsales\Eshop\Application\Controller\Admin\OrderAddress',
            'order_article' => 'OxidEsales\Eshop\Application\Controller\Admin\OrderArticle',
            'order_downloads' => 'OxidEsales\Eshop\Application\Controller\Admin\OrderDownloads',
            'order_main' => 'OxidEsales\Eshop\Application\Controller\Admin\OrderMain',
            'order_overview' => 'OxidEsales\Eshop\Application\Controller\Admin\OrderOverview',
            'order_remark' => 'OxidEsales\Eshop\Application\Controller\Admin\OrderRemark',
            'oxnavigationtree' => 'OxidEsales\Eshop\Application\Controller\Admin\NavigationTree',
            'payment_country' => 'OxidEsales\Eshop\Application\Controller\Admin\PaymentCountry',
            'payment_country_ajax' => 'OxidEsales\Eshop\Application\Controller\Admin\PaymentCountryAjax',
            'payment_list' => 'OxidEsales\Eshop\Application\Controller\Admin\PaymentList',
            'payment_main' => 'OxidEsales\Eshop\Application\Controller\Admin\PaymentMain',
            'payment_main_ajax' => 'OxidEsales\Eshop\Application\Controller\Admin\PaymentMainAjax',
            'payment_rdfa' => 'OxidEsales\Eshop\Application\Controller\Admin\PaymentRdfa',
            'pricealarm_list' => 'OxidEsales\Eshop\Application\Controller\Admin\PriceAlarmList',
            'pricealarm_mail' => 'OxidEsales\Eshop\Application\Controller\Admin\PriceAlarmMail',
            'pricealarm_main' => 'OxidEsales\Eshop\Application\Controller\Admin\PriceAlarmMain',
            'pricealarm_send' => 'OxidEsales\Eshop\Application\Controller\Admin\PriceAlarmSend',
            'selectlist' => 'OxidEsales\Eshop\Application\Controller\Admin\SelectListController',
            'selectlist_list' => 'OxidEsales\Eshop\Application\Controller\Admin\SelectListList',
            'selectlist_main' => 'OxidEsales\Eshop\Application\Controller\Admin\SelectListMain',
            'selectlist_main_ajax' => 'OxidEsales\Eshop\Application\Controller\Admin\SelectListMainAjax',
            'selectlist_order_ajax' => 'OxidEsales\Eshop\Application\Controller\Admin\SelectListOrderAjax',
            'shop' => 'OxidEsales\Eshop\Application\Controller\Admin\ShopController',
            'shop_default_category_ajax' => 'OxidEsales\Eshop\Application\Controller\Admin\ShopDefaultCategoryAjax',
            'shop_license' => 'OxidEsales\Eshop\Application\Controller\Admin\ShopLicense',
            'shop_list' => 'OxidEsales\Eshop\Application\Controller\Admin\ShopList',
            'shop_main' => 'OxidEsales\Eshop\Application\Controller\Admin\ShopMain',
            'shop_performance' => 'OxidEsales\Eshop\Application\Controller\Admin\ShopPerformance',
            'shop_rdfa' => 'OxidEsales\Eshop\Application\Controller\Admin\ShopRdfa',
            'shop_seo' => 'OxidEsales\Eshop\Application\Controller\Admin\ShopSeo',
            'shop_system' => 'OxidEsales\Eshop\Application\Controller\Admin\ShopSystem',
            'sysreq' => 'OxidEsales\Eshop\Application\Controller\Admin\SystemRequirements',
            'sysreq_list' => 'OxidEsales\Eshop\Application\Controller\Admin\SystemRequirementsList',
            'sysreq_main' => 'OxidEsales\Eshop\Application\Controller\Admin\SystemRequirementsMain',
            'systeminfo' => 'OxidEsales\Eshop\Application\Controller\Admin\SystemInfoController',
            'theme_config' => 'OxidEsales\Eshop\Application\Controller\Admin\ThemeConfiguration',
            'theme_list' => 'OxidEsales\Eshop\Application\Controller\Admin\ThemeList',
            'theme_main' => 'OxidEsales\Eshop\Application\Controller\Admin\ThemeMain',
            'tools' => 'OxidEsales\Eshop\Application\Controller\Admin\ToolsController',
            'tools_list' => 'OxidEsales\Eshop\Application\Controller\Admin\ToolsList',
            'tools_main' => 'OxidEsales\Eshop\Application\Controller\Admin\ToolsMain',
            'user_address' => 'OxidEsales\Eshop\Application\Controller\Admin\UserAddress',
            'user_article' => 'OxidEsales\Eshop\Application\Controller\Admin\UserArticle',
            'user_extend' => 'OxidEsales\Eshop\Application\Controller\Admin\UserExtend',
            'user_main' => 'OxidEsales\Eshop\Application\Controller\Admin\UserMain',
            'user_main_ajax' => 'OxidEsales\Eshop\Application\Controller\Admin\UserMainAjax',
            'user_overview' => 'OxidEsales\Eshop\Application\Controller\Admin\UserOverview',
            'user_payment' => 'OxidEsales\Eshop\Application\Controller\Admin\UserPayment',
            'user_remark' => 'OxidEsales\Eshop\Application\Controller\Admin\UserRemark',
            'usergroup' => 'OxidEsales\Eshop\Application\Controller\Admin\UserGroupController',
            'usergroup_list' => 'OxidEsales\Eshop\Application\Controller\Admin\UserGroupList',
            'usergroup_main' => 'OxidEsales\Eshop\Application\Controller\Admin\UserGroupMain',
            'usergroup_main_ajax' => 'OxidEsales\Eshop\Application\Controller\Admin\UserGroupMainAjax',
            'vendor' => 'OxidEsales\Eshop\Application\Controller\Admin\VendorController',
            'vendor_list' => 'OxidEsales\Eshop\Application\Controller\Admin\VendorList',
            'actions_article_ajax' => 'OxidEsales\Eshop\Application\Controller\Admin\ActionsArticleAjax',
            'actions_groups_ajax' => 'OxidEsales\Eshop\Application\Controller\Admin\ActionsGroupsAjax',
            'actions_list' => 'OxidEsales\Eshop\Application\Controller\Admin\ActionsList',
            'actions_main' => 'OxidEsales\Eshop\Application\Controller\Admin\ActionsMain',
            'actions_main_ajax' => 'OxidEsales\Eshop\Application\Controller\Admin\ActionsMainAjax',
            'actions_order_ajax' => 'OxidEsales\Eshop\Application\Controller\Admin\ActionsOrderAjax',
            'admin_content' => 'OxidEsales\Eshop\Application\Controller\Admin\AdminContent',
            'admin_links' => 'OxidEsales\Eshop\Application\Controller\Admin\AdminLinks',
            // @deprecated since v.5.3.0 (2016-06-17); The Admin Menu: Customer Info -> News feature will be moved to a module in v6.0.0
            'admin_news' => 'OxidEsales\Eshop\Application\Controller\Admin\AdminNews',
            // END deprecated
            'admin_newsletter' => 'OxidEsales\Eshop\Application\Controller\Admin\AdminNewsletter',
            'admin_order' => 'OxidEsales\Eshop\Application\Controller\Admin\AdminOrder',
            'admin_payment' => 'OxidEsales\Eshop\Application\Controller\Admin\AdminPayment',
            'admin_pricealarm' => 'OxidEsales\Eshop\Application\Controller\Admin\AdminPriceAlarm',
            'admin_start' => 'OxidEsales\Eshop\Application\Controller\Admin\AdminStart',
            'admin_user' => 'OxidEsales\Eshop\Application\Controller\Admin\AdminUser',
            'admin_wrapping' => 'OxidEsales\Eshop\Application\Controller\Admin\AdminWrapping',
            'adminlinks_list' => 'OxidEsales\Eshop\Application\Controller\Admin\AdminlinksList',
            'adminlinks_main' => 'OxidEsales\Eshop\Application\Controller\Admin\AdminlinksMain',
            'article' => 'OxidEsales\Eshop\Application\Controller\Admin\ArticleController',
            'article_accessories_ajax' => 'OxidEsales\Eshop\Application\Controller\Admin\ArticleAccessoriesAjax',
            'article_attribute' => 'OxidEsales\Eshop\Application\Controller\Admin\ArticleAttribute',
            'article_attribute_ajax' => 'OxidEsales\Eshop\Application\Controller\Admin\ArticleAttributeAjax',
            'article_bundle_ajax' => 'OxidEsales\Eshop\Application\Controller\Admin\ArticleBundleAjax',
            'article_crossselling' => 'OxidEsales\Eshop\Application\Controller\Admin\ArticleCrossselling',
            'article_crossselling_ajax' => 'OxidEsales\Eshop\Application\Controller\Admin\ArticleCrosssellingAjax',
            'article_extend' => 'OxidEsales\Eshop\Application\Controller\Admin\ArticleExtend',
            'article_extend_ajax' => 'OxidEsales\Eshop\Application\Controller\Admin\ArticleExtendAjax',
            'article_files' => 'OxidEsales\Eshop\Application\Controller\Admin\ArticleFiles',
            'article_main' => 'OxidEsales\Eshop\Application\Controller\Admin\ArticleMain',
            'article_overview' => 'OxidEsales\Eshop\Application\Controller\Admin\ArticleOverview',
            'article_pictures' => 'OxidEsales\Eshop\Application\Controller\Admin\ArticlePictures',
            'article_review' => 'OxidEsales\Eshop\Application\Controller\Admin\ArticleReview',
            'article_selection_ajax' => 'OxidEsales\Eshop\Application\Controller\Admin\ArticleSelectionAjax',
            'article_seo' => 'OxidEsales\Eshop\Application\Controller\Admin\ArticleSeo',
            'article_stock' => 'OxidEsales\Eshop\Application\Controller\Admin\ArticleStock',
            'article_userdef' => 'OxidEsales\Eshop\Application\Controller\Admin\ArticleUserdef',
            'article_variant' => 'OxidEsales\Eshop\Application\Controller\Admin\ArticleVariant',
            'attribute' => 'OxidEsales\Eshop\Application\Controller\Admin\AttributeController',
            'attribute_category' => 'OxidEsales\Eshop\Application\Controller\Admin\AttributeCategory',
            'attribute_category_ajax' => 'OxidEsales\Eshop\Application\Controller\Admin\AttributeCategoryAjax',
            'attribute_list' => 'OxidEsales\Eshop\Application\Controller\Admin\AttributeList',
            'attribute_main' => 'OxidEsales\Eshop\Application\Controller\Admin\AttributeMain',
            'attribute_main_ajax' => 'OxidEsales\Eshop\Application\Controller\Admin\AttributeMainAjax',
            'attribute_order_ajax' => 'OxidEsales\Eshop\Application\Controller\Admin\AttributeOrderAjax',
            'category' => 'OxidEsales\Eshop\Application\Controller\Admin\CategoryController',
            'category_list' => 'OxidEsales\Eshop\Application\Controller\Admin\CategoryList',
            'category_main' => 'OxidEsales\Eshop\Application\Controller\Admin\CategoryMain',
            'category_main_ajax' => 'OxidEsales\Eshop\Application\Controller\Admin\CategoryMainAjax',
            'category_order' => 'OxidEsales\Eshop\Application\Controller\Admin\CategoryOrder',
            'category_order_ajax' => 'OxidEsales\Eshop\Application\Controller\Admin\CategoryOrderAjax',
            'category_pictures' => 'OxidEsales\Eshop\Application\Controller\Admin\CategoryPictures',
            'category_seo' => 'OxidEsales\Eshop\Application\Controller\Admin\CategorySeo',
            'category_text' => 'OxidEsales\Eshop\Application\Controller\Admin\CategoryText',
            'category_update' => 'OxidEsales\Eshop\Application\Controller\Admin\CategoryUpdate',
            'content_list' => 'OxidEsales\Eshop\Application\Controller\Admin\ContentList',
            'content_main' => 'OxidEsales\Eshop\Application\Controller\Admin\ContentMain',
            'content_seo' => 'OxidEsales\Eshop\Application\Controller\Admin\ContentSeo',
            'country' => 'OxidEsales\Eshop\Application\Controller\Admin\CountryController',
            'country_list' => 'OxidEsales\Eshop\Application\Controller\Admin\CountryList',
            'country_main' => 'OxidEsales\Eshop\Application\Controller\Admin\CountryMain',
            'delivery' => 'OxidEsales\Eshop\Application\Controller\Admin\DeliveryController',
            'delivery_articles' => 'OxidEsales\Eshop\Application\Controller\Admin\DeliveryArticles',
            'delivery_articles_ajax' => 'OxidEsales\Eshop\Application\Controller\Admin\DeliveryArticlesAjax',
            'delivery_categories_ajax' => 'OxidEsales\Eshop\Application\Controller\Admin\DeliveryCategoriesAjax',
            'delivery_groups_ajax' => 'OxidEsales\Eshop\Application\Controller\Admin\DeliveryGroupsAjax',
            'delivery_list' => 'OxidEsales\Eshop\Application\Controller\Admin\DeliveryList',
            'delivery_main' => 'OxidEsales\Eshop\Application\Controller\Admin\DeliveryMain',
            'delivery_main_ajax' => 'OxidEsales\Eshop\Application\Controller\Admin\DeliveryMainAjax',
            'delivery_users' => 'OxidEsales\Eshop\Application\Controller\Admin\DeliveryUsers',
            'delivery_users_ajax' => 'OxidEsales\Eshop\Application\Controller\Admin\DeliveryUsersAjax',
            'deliveryset' => 'OxidEsales\Eshop\Application\Controller\Admin\DeliverySetController',
            'deliveryset_country_ajax' => 'OxidEsales\Eshop\Application\Controller\Admin\DeliverySetCountryAjax',
            'deliveryset_groups_ajax' => 'OxidEsales\Eshop\Application\Controller\Admin\DeliverySetGroupsAjax',
            'deliveryset_list' => 'OxidEsales\Eshop\Application\Controller\Admin\DeliverySetList',
            'deliveryset_main' => 'OxidEsales\Eshop\Application\Controller\Admin\DeliverySetMain',
            'deliveryset_main_ajax' => 'OxidEsales\Eshop\Application\Controller\Admin\DeliverySetMainAjax',
            'deliveryset_payment' => 'OxidEsales\Eshop\Application\Controller\Admin\DeliverySetPayment',
            'deliveryset_payment_ajax' => 'OxidEsales\Eshop\Application\Controller\Admin\DeliverySetPaymentAjax',
            'deliveryset_rdfa' => 'OxidEsales\Eshop\Application\Controller\Admin\DeliverySetRdfa',
            'deliveryset_users' => 'OxidEsales\Eshop\Application\Controller\Admin\DeliverySetUsers',
            'deliveryset_users_ajax' => 'OxidEsales\Eshop\Application\Controller\Admin\DeliverySetUsersAjax',
            'diagnostics' => 'OxidEsales\Eshop\Application\Controller\Admin\DiagnosticsController',
            'diagnostics_list' => 'OxidEsales\Eshop\Application\Controller\Admin\DiagnosticsList',
            'diagnostics_main' => 'OxidEsales\Eshop\Application\Controller\Admin\DiagnosticsMain',
            'discount' => 'OxidEsales\Eshop\Application\Controller\Admin\DiscountController',
            'discount_articles' => 'OxidEsales\Eshop\Application\Controller\Admin\DiscountArticles',
            'discount_articles_ajax' => 'OxidEsales\Eshop\Application\Controller\Admin\DiscountArticlesAjax',
            'discount_categories_ajax' => 'OxidEsales\Eshop\Application\Controller\Admin\DiscountCategoriesAjax',
            'discount_groups_ajax' => 'OxidEsales\Eshop\Application\Controller\Admin\DiscountGroupsAjax',
            'discount_item_ajax' => 'OxidEsales\Eshop\Application\Controller\Admin\DiscountItemAjax',
            'discount_list' => 'OxidEsales\Eshop\Application\Controller\Admin\DiscountList',
            'discount_main' => 'OxidEsales\Eshop\Application\Controller\Admin\DiscountMain',
            'discount_main_ajax' => 'OxidEsales\Eshop\Application\Controller\Admin\DiscountMainAjax',
            'discount_users' => 'OxidEsales\Eshop\Application\Controller\Admin\DiscountUsers',
            'discount_users_ajax' => 'OxidEsales\Eshop\Application\Controller\Admin\DiscountUsersAjax',
            'dyn_econda' => 'OxidEsales\Eshop\Application\Controller\Admin\DynEconda',

            'content' => 'OxidEsales\Eshop\Application\Controller\ContentController',
            'links' => 'OxidEsales\Eshop\Application\Controller\LinksController',
            // @deprecated since v.5.3.0 (2016-06-17); The Admin Menu: Customer Info -> News feature will be moved to a module in v6.0.0
            'news' => 'OxidEsales\Eshop\Application\Controller\NewsController',
            // END deprecated
            'newsletter' => 'OxidEsales\Eshop\Application\Controller\NewsletterController',
            'pricealarm' => 'OxidEsales\Eshop\Application\Controller\PriceAlarmController',

        ];
    }

    /**
     * @inheritdoc
     */
    public function getNotOverridableMap()
    {
        return [
            'oxbase' => '\OxidEsales\Eshop\Core\Base',
            'oxsysrequirements' => '\OxidEsales\Eshop\Core\SystemRequirements',
            'oxadminview' => '\OxidEsales\Eshop\Application\Controller\Admin\AdminView',
            'oxadminlist' => '\OxidEsales\Eshop\Application\Controller\Admin\AdminList',
            'order_list' => '\OxidEsales\Eshop\Application\Controller\Admin\OrderList',
            'user_list' => '\OxidEsales\Eshop\Application\Controller\Admin\UserList',
            'oxadmindetails' => '\OxidEsales\Eshop\Application\Controller\Admin\AdminDetails',
            'ajaxlistcomponent' => '\OxidEsales\Eshop\Application\Controller\Admin\ListComponentAjax',
            'article_list' => '\OxidEsales\Eshop\Application\Controller\Admin\ArticleList',
            'oxshopidcalculator' => '\OxidEsales\Eshop\Core\ShopIdCalculator',
            'details' => '\OxidEsales\Eshop\Application\Controller\ArticleDetailsController',
            'oxubase' => '\OxidEsales\Eshop\Application\Controller\BaseController',
            'alist' => '\OxidEsales\Eshop\Application\Controller\ArticleListController',
            'user' => '\OxidEsales\Eshop\Application\Controller\UserController',
            'guestbook' => '\OxidEsales\Eshop\Application\Controller\GuestbookController',
            'account' => '\OxidEsales\Eshop\Application\Controller\AccountController',
            'basket' => '\OxidEsales\Eshop\Application\Controller\BasketController',
            'compare' => '\OxidEsales\Eshop\Application\Controller\CompareController',
            'order' => '\OxidEsales\Eshop\Application\Controller\OrderController',
            'payment' => '\OxidEsales\Eshop\Application\Controller\PaymentController',
            'recommlist' => '\OxidEsales\Eshop\Application\Controller\RecommListController',
            'rss' => '\OxidEsales\Eshop\Application\Controller\RssController',
            'search' => '\OxidEsales\Eshop\Application\Controller\SearchController',
            'start' => '\OxidEsales\Eshop\Application\Controller\StartController',
            'thankyou' => '\OxidEsales\Eshop\Application\Controller\ThankYouController',
            'wishlist' => '\OxidEsales\Eshop\Application\Controller\WishListController',
            'wrapping' => '\OxidEsales\Eshop\Application\Controller\WrappingController',
            'oxshopcontrol' => '\OxidEsales\Eshop\Core\ShopControl',
            'oxview' => '\OxidEsales\Eshop\Core\View',
            'oxi18n' => '\OxidEsales\Eshop\Core\I18n',
            'oxsupercfg' => '\OxidEsales\Eshop\Core\SuperConfig',
            'oxutilsobject' => '\OxidEsales\Eshop\Core\UtilsObject',
            'oxdb' => '\OxidEsales\Eshop\Core\Database',
            'oxconnectionexception' => '\OxidEsales\Eshop\Core\Exception\ConnectionException',
            'oxdynimggenerator' => '\OxidEsales\Eshop\Core\DynamicImageGenerator',
            'oxexceptiontodisplay' => '\OxidEsales\Eshop\Core\Exception\ExceptionToDisplay',
            'oxfield' => '\OxidEsales\Eshop\Core\Field',
            'oxlist' => '\OxidEsales\Eshop\Core\StandardList',
            'oxseoencoder' => '\OxidEsales\Eshop\Core\SeoEncoder',
            'oxstdclass' => '\OxidEsales\Eshop\Core\StandardClass',
            'oxsystemcomponentexception' => '\OxidEsales\Eshop\Core\Exception\SystemComponentException',
            'oxconfigfile' => '\OxidEsales\Eshop\Core\ConfigFile',
            'oxregistry' => '\OxidEsales\Eshop\Core\Registry',
            'oxstart' => '\OxidEsales\Eshop\Application\Controller\OxidStartController',
            'dyn_interface' => '\OxidEsales\Eshop\Application\Controller\Admin\DynamicInterface',
            'dyn_screen' => '\OxidEsales\Eshop\Application\Controller\Admin\DynamicScreen',
            'dynexportbase' => '\OxidEsales\Eshop\Application\Controller\Admin\DynamicExportBaseController',
            'genimport_main' => '\OxidEsales\Eshop\Application\Controller\Admin\GenericImportMain',
            'object_seo' => '\OxidEsales\Eshop\Application\Controller\Admin\ObjectSeo',
            'shop_config' => '\OxidEsales\Eshop\Application\Controller\Admin\ShopConfiguration',

            'oxvoucherexception' => '\OxidEsales\Eshop\Core\Exception\VoucherException',
            'oxuserexception' => '\OxidEsales\Eshop\Core\Exception\UserException',
            'oxshopexception' => '\OxidEsales\Eshop\Core\Exception\ShopException',
            'oxoutofstockexception' => '\OxidEsales\Eshop\Core\Exception\OutOfStockException',
            'oxobjectexception' => '\OxidEsales\Eshop\Core\Exception\ObjectException',
            'oxnoarticleexception' => '\OxidEsales\Eshop\Core\Exception\NoArticleException',
            'oxinputexception' => '\OxidEsales\Eshop\Core\Exception\InputException',
            'oxfileexception' => '\OxidEsales\Eshop\Core\Exception\FileException',
            'oxexceptionhandler' => '\OxidEsales\Eshop\Core\Exception\ExceptionHandler',
            'oxexception' => '\OxidEsales\Eshop\Core\Exception\StandardException',
            'oxcookieexception' => '\OxidEsales\Eshop\Core\Exception\CookieException',
            'oxarticleinputexception' => '\OxidEsales\Eshop\Core\Exception\ArticleInputException',
            'oxarticleexception' => '\OxidEsales\Eshop\Core\Exception\ArticleException',
            'oxlanguageexception' => '\OxidEsales\Eshop\Core\Exception\LanguageException',

            'oxmodule' => '\OxidEsales\Eshop\Core\Module',
            'oxmodulecache' => '\OxidEsales\Eshop\Core\ModuleCache',
            'oxmodulefilesvalidator' => '\OxidEsales\Eshop\Core\ModuleFilesValidator',
            'oxonlinemoduleversionnotifier' => '\OxidEsales\Eshop\Core\OnlineModuleVersionNotifier',
            'oxmodulelist' => '\OxidEsales\Eshop\Core\ModuleList',
            'oxmodulemetadatavalidator' => '\OxidEsales\Eshop\Core\ModuleMetadataValidator',
            'oxcurl' => '\OxidEsales\Eshop\Core\Curl',
            'oxonlineserveremailbuilder' => '\OxidEsales\Eshop\Core\OnlineServerEmailBuilder',
            'oxonlinelicensecheckrequest' => '\OxidEsales\Eshop\Core\OnlineLicenseCheckRequest',
            'oxonlinerequest' => '\OxidEsales\Eshop\Core\OnlineRequest',
            'oxonlinelicensecheck' => '\OxidEsales\Eshop\Core\OnlineLicenseCheck',
            'oxonlinemoduleversionnotifiercaller' => '\OxidEsales\Eshop\Core\OnlineModuleVersionNotifierCaller',
            'oxonlinemodulesnotifierrequest' => '\OxidEsales\Eshop\Core\OnlineModulesNotifierRequest',
            'oxconfig' => '\OxidEsales\Eshop\Core\Config',
            'oxlang' => '\OxidEsales\Eshop\Core\Language',
            'oxcompanyvatinvalidator' => '\OxidEsales\Eshop\Core\CompanyVatInValidator',
            'oxcompanyvatincountrychecker' => '\OxidEsales\Eshop\Core\CompanyVatInCountryChecker',
            'oxonlinevatidcheck' => '\OxidEsales\Eshop\Core\OnlineVatIdCheck',

            'oxserversmanager' => '\OxidEsales\Eshop\Core\ServersManager',
            'oxserverchecker' => '\OxidEsales\Eshop\Core\ServerChecker',
            'oxutilsserver' => '\OxidEsales\Eshop\Core\UtilsServer',
            'oxutilsdate' => '\OxidEsales\Eshop\Core\UtilsDate',
            'oxoutput' => '\OxidEsales\Eshop\Core\Output',
            'oxutilspic' => '\OxidEsales\Eshop\Core\UtilsPic',
            'oxutils' => '\OxidEsales\Eshop\Core\Utils',

            'oxprice' => '\OxidEsales\Eshop\Core\Price',
            'oxsimplexml' => '\OxidEsales\Eshop\Core\SimpleXml',
            'oxopensslfunctionalitychecker' => '\OxidEsales\Eshop\Core\OpenSSLFunctionalityChecker',
            'oxstrmb' => '\OxidEsales\Eshop\Core\StrMb',
            'oxstr' => '\OxidEsales\Eshop\Core\Str',
            'oxsession' => '\OxidEsales\Eshop\Core\Session',
            'oxtheme' => '\OxidEsales\Eshop\Core\Theme',
            'oxpricelist' => '\OxidEsales\Eshop\Core\PriceList',
            'oxdisplayerror' => '\OxidEsales\Eshop\Core\DisplayError',

            'oxiconfigurable' => '\OxidEsales\Eshop\Core\Contract\IConfigurable',
            'oxicountryaware' => '\OxidEsales\Eshop\Core\Contract\ICountryAware',
            'oxidisplayerror' => '\OxidEsales\Eshop\Core\Contract\IDisplayError',
            'oximodulevalidator' => '\OxidEsales\Eshop\Core\Contract\IModuleValidator',
            'oxiselectlist' => '\OxidEsales\Eshop\Core\Contract\ISelectList',
            'oxiurl' => '\OxidEsales\Eshop\Core\Contract\IUrl',

            'oxactionlist' => 'OxidEsales\Eshop\Application\Model\ActionList',
            'oxactions' => 'OxidEsales\Eshop\Application\Model\Actions',
            'oxaddress' => 'OxidEsales\Eshop\Application\Model\Address',
            'oxamountpricelist' => 'OxidEsales\Eshop\Application\Model\AmountPriceList',
            'oxarticlelist' => 'OxidEsales\Eshop\Application\Model\ArticleList',
            'oxattribute' => 'OxidEsales\Eshop\Application\Model\Attribute',
            'oxattributelist' => 'OxidEsales\Eshop\Application\Model\AttributeList',
            'oxbasket' => 'OxidEsales\Eshop\Application\Model\Basket',
            'oxbasketcontentmarkgenerator' => 'OxidEsales\Eshop\Application\Model\BasketContentMarkGenerator',
            'oxbasketitem' => 'OxidEsales\Eshop\Application\Model\BasketItem',
            'oxbasketreservation' => 'OxidEsales\Eshop\Application\Model\BasketReservation',
            'oxcategory' => 'OxidEsales\Eshop\Application\Model\Category',
            'oxcategorylist' => 'OxidEsales\Eshop\Application\Model\CategoryList',
            'oxcompanyvatin' => 'OxidEsales\Eshop\Application\Model\CompanyVatIn',
            'oxcontent' => 'OxidEsales\Eshop\Application\Model\Content',
            'oxcontentlist' => 'OxidEsales\Eshop\Application\Model\ContentList',
            'oxcountry' => 'OxidEsales\Eshop\Application\Model\Country',
            'oxcountrylist' => 'OxidEsales\Eshop\Application\Model\CountryList',
            'oxdelivery' => 'OxidEsales\Eshop\Application\Model\Delivery',
            'oxdeliverylist' => 'OxidEsales\Eshop\Application\Model\DeliveryList',
            'oxdeliveryset' => 'OxidEsales\Eshop\Application\Model\DeliverySet',
            'oxdeliverysetlist' => 'OxidEsales\Eshop\Application\Model\DeliverySetList',
            'oxdiagnostics' => 'OxidEsales\Eshop\Application\Model\Diagnostics',
            'oxdiagnosticsoutput' => 'OxidEsales\Eshop\Application\Model\DiagnosticsOutput',
            'oxdiscount' => 'OxidEsales\Eshop\Application\Model\Discount',
            'oxdiscountlist' => 'OxidEsales\Eshop\Application\Model\DiscountList',
            'oxfile' => 'OxidEsales\Eshop\Application\Model\File',
            'oxfilechecker' => 'OxidEsales\Eshop\Application\Model\FileChecker',
            'oxfilecheckerresult' => 'OxidEsales\Eshop\Application\Model\FileCheckerResult',
            'oxfilecollector' => 'OxidEsales\Eshop\Application\Model\FileCollector',
            'oxgroups' => 'OxidEsales\Eshop\Application\Model\Groups',
            'oxlinks' => 'OxidEsales\Eshop\Application\Model\Links',
            'oxlistobject' => 'OxidEsales\Eshop\Application\Model\ListObject',
            'oxmaintenance' => 'OxidEsales\Eshop\Application\Model\Maintenance',
            'oxmanufacturer' => 'OxidEsales\Eshop\Application\Model\Manufacturer',
            'oxmanufacturerlist' => 'OxidEsales\Eshop\Application\Model\ManufacturerList',
            'oxmdvariant' => 'OxidEsales\Eshop\Application\Model\MdVariant',
            'oxmediaurl' => 'OxidEsales\Eshop\Application\Model\MediaUrl',
            // @deprecated since v.5.3.0 (2016-06-17); The Admin Menu: Customer Info -> News feature will be moved to a module in v6.0.0
            'oxnews' => 'OxidEsales\Eshop\Application\Model\News',
            // END deprecated
            'oxnewsletter' => 'OxidEsales\Eshop\Application\Model\Newsletter',
            'oxnewslist' => 'OxidEsales\Eshop\Application\Model\NewsList',
            'oxnewssubscribed' => 'OxidEsales\Eshop\Application\Model\NewsSubscribed',
            'oxobject2category' => 'OxidEsales\Eshop\Application\Model\Object2Category',
            'oxobject2group' => 'OxidEsales\Eshop\Application\Model\Object2Group',
            'oxorder' => 'OxidEsales\Eshop\Application\Model\Order',
            'oxorderarticlelist' => 'OxidEsales\Eshop\Application\Model\OrderArticleList',
            'oxorderfile' => 'OxidEsales\Eshop\Application\Model\OrderFile',
            'oxorderfilelist' => 'OxidEsales\Eshop\Application\Model\OrderFileList',
            'oxpayment' => 'OxidEsales\Eshop\Application\Model\Payment',
            'oxpaymentgateway' => 'OxidEsales\Eshop\Application\Model\PaymentGateway',
            'oxpaymentlist' => 'OxidEsales\Eshop\Application\Model\PaymentList',
            'oxpricealarm' => 'OxidEsales\Eshop\Application\Model\PriceAlarm',
            'oxrating' => 'OxidEsales\Eshop\Application\Model\Rating',
            'oxrecommlist' => 'OxidEsales\Eshop\Application\Model\RecommendationList',
            'oxremark' => 'OxidEsales\Eshop\Application\Model\Remark',
            'oxrequiredaddressfields' => 'OxidEsales\Eshop\Application\Model\RequiredAddressFields',
            'oxrequiredfieldsvalidator' => 'OxidEsales\Eshop\Application\Model\RequiredFieldsValidator',
            'oxrequiredfieldvalidator' => 'OxidEsales\Eshop\Application\Model\RequiredFieldValidator',
            'oxreview' => 'OxidEsales\Eshop\Application\Model\Review',
            'oxrssfeed' => 'OxidEsales\Eshop\Application\Model\RssFeed',
            'oxsearch' => 'OxidEsales\Eshop\Application\Model\Search',
            'oxselection' => 'OxidEsales\Eshop\Application\Model\Selection',
            'oxselectlist' => 'OxidEsales\Eshop\Application\Model\SelectList',
            'oxseoencoderarticle' => 'OxidEsales\Eshop\Application\Model\SeoEncoderArticle',
            'oxseoencodercategory' => 'OxidEsales\Eshop\Application\Model\SeoEncoderCategory',
            'oxseoencodercontent' => 'OxidEsales\Eshop\Application\Model\SeoEncoderContent',
            'oxseoencodermanufacturer' => 'OxidEsales\Eshop\Application\Model\SeoEncoderManufacturer',
            'oxseoencoderrecomm' => 'OxidEsales\Eshop\Application\Model\SeoEncoderRecomm',
            'oxseoencodervendor' => 'OxidEsales\Eshop\Application\Model\SeoEncoderVendor',
            'oxshop' => 'OxidEsales\Eshop\Application\Model\Shop',
            'oxshoplist' => 'OxidEsales\Eshop\Application\Model\ShopList',
            'oxshopviewvalidator' => 'OxidEsales\Eshop\Application\Model\ShopViewValidator',
            'oxsimplevariant' => 'OxidEsales\Eshop\Application\Model\SimpleVariant',
            'oxsimplevariantlist' => 'OxidEsales\Eshop\Application\Model\SimpleVariantList',
            'oxsmartyrenderer' => 'OxidEsales\Eshop\Application\Model\SmartyRenderer',
            'oxstate' => 'OxidEsales\Eshop\Application\Model\State',
            'oxuser' => 'OxidEsales\Eshop\Application\Model\User',
            'oxuseraddresslist' => 'OxidEsales\Eshop\Application\Model\UserAddressList',
            'oxuserbasket' => 'OxidEsales\Eshop\Application\Model\UserBasket',
            'oxuserbasketitem' => 'OxidEsales\Eshop\Application\Model\UserBasketItem',
            'oxuserlist' => 'OxidEsales\Eshop\Application\Model\UserList',
            'oxuserpayment' => 'OxidEsales\Eshop\Application\Model\UserPayment',
            'oxvarianthandler' => 'OxidEsales\Eshop\Application\Model\VariantHandler',
            'oxvariantselectlist' => 'OxidEsales\Eshop\Application\Model\VariantSelectList',
            'oxvatselector' => 'OxidEsales\Eshop\Application\Model\VatSelector',
            'oxvendor' => 'OxidEsales\Eshop\Application\Model\Vendor',
            'oxvendorlist' => 'OxidEsales\Eshop\Application\Model\VendorList',
            'oxvoucher' => 'OxidEsales\Eshop\Application\Model\Voucher',
            'oxvoucherlist' => 'OxidEsales\Eshop\Application\Model\VoucherList',
            'oxvoucherserie' => 'OxidEsales\Eshop\Application\Model\VoucherSerie',
            'oxwrapping' => 'OxidEsales\Eshop\Application\Model\Wrapping',
        ];
    }
}
