<?php
/**
 * This file is part of OXID eShop Community Edition.
 *
 * OXID eShop Community Edition is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * OXID eShop Community Edition is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with OXID eShop Community Edition.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @link      http://www.oxid-esales.com
 * @copyright (C) OXID eSales AG 2003-2016
 * @version   OXID eShop CE
 */

namespace OxidEsales\EshopCommunity\Core;

use OxidEsales\EshopCommunity\Application\Component\Widget\WidgetController;
use OxidEsales\EshopCommunity\Application\Controller\Admin\AdminController;
use OxidEsales\EshopCommunity\Application\Controller\Admin\AdminDetailsController;
use OxidEsales\EshopCommunity\Application\Controller\Admin\AdminListController;
use OxidEsales\EshopCommunity\Application\Controller\FrontendController;
use OxidEsales\EshopCommunity\Core\Controller\BaseController;
use OxidEsales\EshopCommunity\Core\Model\ListModel;
use OxidEsales\EshopCommunity\Core\Model\MultiLanguageModel;

/**
 * @inheritdoc
 */
class ClassMap extends \OxidEsales\EshopCommunity\Core\Edition\ClassMap
{

    /**
     * @inheritdoc
     */
    public function getOverridableMap()
    {
        return [
            'oxdbmetadatahandler'                  => \OxidEsales\EshopCommunity\Core\DbMetaDataHandler::class,
            'oxApplicationServer'                  => \OxidEsales\EshopCommunity\Core\ApplicationServer::class,
            'oxCcValidator'                        => \OxidEsales\EshopCommunity\Core\CreditCardValidator::class,
            'language'                             => \OxidEsales\EshopCommunity\Application\Controller\Admin\LanguageController::class,
            'module'                               => \OxidEsales\EshopCommunity\Application\Controller\Admin\ModuleController::class,
            'theme'                                => \OxidEsales\EshopCommunity\Application\Controller\Admin\ThemeController::class,
            'oxcompanyvatinchecker'                => \OxidEsales\EshopCommunity\Core\CompanyVatInChecker::class,
            'oxcounter'                            => \OxidEsales\EshopCommunity\Core\Counter::class,
            'oxdebuginfo'                          => \OxidEsales\EshopCommunity\Core\DebugInfo::class,
            'oxdecryptor'                          => \OxidEsales\EshopCommunity\Core\Decryptor::class,
            'oxemail'                              => \OxidEsales\EshopCommunity\Core\Email::class,
            'oxencryptor'                          => \OxidEsales\EshopCommunity\Core\Encryptor::class,
            'oxfilecache'                          => \OxidEsales\EshopCommunity\Core\FileCache::class,
            'oxhasher'                             => \OxidEsales\EshopCommunity\Core\Hasher::class,
            'oxheader'                             => \OxidEsales\EshopCommunity\Core\Header::class,
            'oxinputvalidator'                     => \OxidEsales\EshopCommunity\Core\InputValidator::class,
            'oxmodulechainsgenerator'              => \OxidEsales\EshopCommunity\Core\ModuleChainsGenerator::class,
            'oxmoduleinstaller'                    => \OxidEsales\EshopCommunity\Core\ModuleInstaller::class,
            'oxmodulemetadataagainstshopvalidator' => \OxidEsales\EshopCommunity\Core\ModuleMetadataAgainstShopValidator::class,
            'oxmodulevalidatorfactory'             => \OxidEsales\EshopCommunity\Core\ModuleValidatorFactory::class,
            'oxmodulevariableslocator'             => \OxidEsales\EshopCommunity\Core\ModuleVariablesLocator::class,
            'oxnojsvalidator'                      => \OxidEsales\EshopCommunity\Core\NoJsValidator::class,
            'oxonlinecaller'                       => \OxidEsales\EshopCommunity\Core\OnlineCaller::class,
            'oxonlinelicensecheckcaller'           => \OxidEsales\EshopCommunity\Core\OnlineLicenseCheckCaller::class,
            'oxonlinelicensecheckresponse'         => \OxidEsales\EshopCommunity\Core\OnlineLicenseCheckResponse::class,
            'oxpasswordhasher'                     => \OxidEsales\EshopCommunity\Core\PasswordHasher::class,
            'oxpasswordsaltgenerator'              => \OxidEsales\EshopCommunity\Core\PasswordSaltGenerator::class,
            'oxpdf'                                => \OxidEsales\EshopCommunity\Core\Pdf::class,
            'oxpicturehandler'                     => \OxidEsales\EshopCommunity\Core\PictureHandler::class,
            'oxseodecoder'                         => \OxidEsales\EshopCommunity\Core\SeoDecoder::class,
            'oxsepabicvalidator'                   => \OxidEsales\EshopCommunity\Core\SepaBICValidator::class,
            'oxsepaibanvalidator'                  => \OxidEsales\EshopCommunity\Core\SepaIBANValidator::class,
            'oxsepavalidator'                      => \OxidEsales\EshopCommunity\Core\SepaValidator::class,
            'oxserverprocessor'                    => \OxidEsales\EshopCommunity\Core\ServerProcessor::class,
            'oxsha512hasher'                       => \OxidEsales\EshopCommunity\Core\Sha512Hasher::class,
            'oxstrregular'                         => \OxidEsales\EshopCommunity\Core\StrRegular::class,
            'oxsubshopspecificfilecache'           => \OxidEsales\EshopCommunity\Core\SubShopSpecificFileCache::class,
            'oxsystemeventhandler'                 => \OxidEsales\EshopCommunity\Core\SystemEventHandler::class,
            'oxtableviewnamegenerator'             => \OxidEsales\EshopCommunity\Core\TableViewNameGenerator::class,
            'oxuniversallyuniqueidgenerator'       => \OxidEsales\EshopCommunity\Core\UniversallyUniqueIdGenerator::class,
            'oxusercounter'                        => \OxidEsales\EshopCommunity\Core\UserCounter::class,
            'oxutilscount'                         => \OxidEsales\EshopCommunity\Core\UtilsCount::class,
            'oxutilsfile'                          => \OxidEsales\EshopCommunity\Core\UtilsFile::class,
            'oxutilsstring'                        => \OxidEsales\EshopCommunity\Core\UtilsString::class,
            'oxutilsurl'                           => \OxidEsales\EshopCommunity\Core\UtilsUrl::class,
            'oxutilsview'                          => \OxidEsales\EshopCommunity\Core\UtilsView::class,
            'oxutilsxml'                           => \OxidEsales\EshopCommunity\Core\UtilsXml::class,
            'oxviewconfig'                         => \OxidEsales\EshopCommunity\Core\ViewConfig::class,
            'oxwidgetcontrol'                      => \OxidEsales\EshopCommunity\Core\WidgetControl::class,
            'emos'                                 => \OxidEsales\EshopCommunity\Core\Smarty\Plugin\Emos::class,
            'emos_item'                            => \OxidEsales\EshopCommunity\Core\Smarty\Plugin\EmosItem::class,
            'oxemosadapter'                        => \OxidEsales\EshopCommunity\Core\Smarty\Plugin\EmosAdapter::class,
            'manufacturerlist'                     => \OxidEsales\EshopCommunity\Application\Controller\ManufacturerListController::class,
            'review'                               => \OxidEsales\EshopCommunity\Application\Controller\ReviewController::class,
            'vendorlist'                           => \OxidEsales\EshopCommunity\Application\Controller\VendorListController::class,
            'actions'                              => \OxidEsales\EshopCommunity\Application\Controller\Admin\ActionsController::class,
            'oxwactions'                           => \OxidEsales\EshopCommunity\Application\Component\Widget\Actions::class,
            'oxwbetanote'                          => \OxidEsales\EshopCommunity\Application\Component\Widget\BetaNote::class,
            'oxwcategorytree'                      => \OxidEsales\EshopCommunity\Application\Component\Widget\CategoryTree::class,
            'oxwinformation'                       => \OxidEsales\EshopCommunity\Application\Component\Widget\Information::class,
            'oxwrating'                            => \OxidEsales\EshopCommunity\Application\Component\Widget\Rating::class,
            'oxwservicemenu'                       => \OxidEsales\EshopCommunity\Application\Component\Widget\ServiceMenu::class,
            'oxwarticlebox'                        => \OxidEsales\EshopCommunity\Application\Component\Widget\ArticleBox::class,
            'oxwcookienote'                        => \OxidEsales\EshopCommunity\Application\Component\Widget\CookieNote::class,
            'oxwlanguagelist'                      => \OxidEsales\EshopCommunity\Application\Component\Widget\LanguageList::class,
            'oxwrecommendation'                    => \OxidEsales\EshopCommunity\Application\Component\Widget\Recommendation::class,
            'oxwarticledetails'                    => \OxidEsales\EshopCommunity\Application\Component\Widget\ArticleDetails::class,
            'oxwcurrencylist'                      => \OxidEsales\EshopCommunity\Application\Component\Widget\CurrencyList::class,
            'oxwmanufacturerlist'                  => \OxidEsales\EshopCommunity\Application\Component\Widget\ManufacturerList::class,
            'oxwreview'                            => \OxidEsales\EshopCommunity\Application\Component\Widget\Review::class,
            'oxwvendorlist'                        => \OxidEsales\EshopCommunity\Application\Component\Widget\VendorList::class,
            'oxwidget'                             => WidgetController::class,
            'oxwminibasket'                        => \OxidEsales\EshopCommunity\Application\Component\Widget\MiniBasket::class,
            'oxwservicelist'                       => \OxidEsales\EshopCommunity\Application\Component\Widget\ServiceList::class,
            'oxcmp_categories'                     => \OxidEsales\EshopCommunity\Application\Component\CategoriesComponent::class,
            'oxcmp_lang'                           => \OxidEsales\EshopCommunity\Application\Component\LanguageComponent::class,
            'oxcmp_shop'                           => \OxidEsales\EshopCommunity\Application\Component\ShopComponent::class,
            'oxcmp_utils'                          => \OxidEsales\EshopCommunity\Application\Component\UtilsComponent::class,
            'oxcmp_basket'                         => \OxidEsales\EshopCommunity\Application\Component\BasketComponent::class,
            'oxcmp_cur'                            => \OxidEsales\EshopCommunity\Application\Component\CurrencyComponent::class,
            'oxcmp_news'                           => \OxidEsales\EshopCommunity\Application\Component\NewsComponent::class,
            'oxcmp_user'                           => \OxidEsales\EshopCommunity\Application\Component\UserComponent::class,
            'oxlocator'                            => \OxidEsales\EshopCommunity\Application\Component\Locator::class,
            'account_user'                         => \OxidEsales\EshopCommunity\Application\Controller\AccountUserController::class,
            'account_wishlist'                     => \OxidEsales\EshopCommunity\Application\Controller\AccountWishlistController::class,
            'vendor_main'                          => \OxidEsales\EshopCommunity\Application\Controller\Admin\VendorMain::class,
            'vendor_main_ajax'                     => \OxidEsales\EshopCommunity\Application\Controller\Admin\VendorMainAjax::class,
            'vendor_seo'                           => \OxidEsales\EshopCommunity\Application\Controller\Admin\VendorSeo::class,
            'voucherserie'                         => \OxidEsales\EshopCommunity\Application\Controller\Admin\VoucherSerieController::class,
            'voucherserie_export'                  => \OxidEsales\EshopCommunity\Application\Controller\Admin\VoucherSerieExport::class,
            'voucherserie_generate'                => \OxidEsales\EshopCommunity\Application\Controller\Admin\VoucherSerieGenerate::class,
            'voucherserie_groups'                  => \OxidEsales\EshopCommunity\Application\Controller\Admin\VoucherSerieGroups::class,
            'voucherserie_groups_ajax'             => \OxidEsales\EshopCommunity\Application\Controller\Admin\VoucherSerieGroupsAjax::class,
            'voucherserie_list'                    => \OxidEsales\EshopCommunity\Application\Controller\Admin\VoucherSerieList::class,
            'voucherserie_main'                    => \OxidEsales\EshopCommunity\Application\Controller\Admin\VoucherSerieMain::class,
            'wrapping_list'                        => \OxidEsales\EshopCommunity\Application\Controller\Admin\WrappingList::class,
            'wrapping_main'                        => \OxidEsales\EshopCommunity\Application\Controller\Admin\WrappingMain::class,
            'dynscreen'                            => \OxidEsales\EshopCommunity\Application\Controller\Admin\DynamicScreenController::class,
            'dynscreen_list'                       => \OxidEsales\EshopCommunity\Application\Controller\Admin\DynamicScreenList::class,
            'dynscreen_local'                      => \OxidEsales\EshopCommunity\Application\Controller\Admin\DynamicScreenLocal::class,
            'genexport'                            => \OxidEsales\EshopCommunity\Application\Controller\Admin\GenericExport::class,
            'genexport_do'                         => \OxidEsales\EshopCommunity\Application\Controller\Admin\GenericExportDo::class,
            'genexport_main'                       => \OxidEsales\EshopCommunity\Application\Controller\Admin\GenericExportMain::class,
            'genimport'                            => \OxidEsales\EshopCommunity\Application\Controller\Admin\GenericImport::class,
            'language_list'                        => \OxidEsales\EshopCommunity\Application\Controller\Admin\LanguageList::class,
            'language_main'                        => \OxidEsales\EshopCommunity\Application\Controller\Admin\LanguageMain::class,
            'list_review'                          => \OxidEsales\EshopCommunity\Application\Controller\Admin\ListReview::class,
            'list_user'                            => \OxidEsales\EshopCommunity\Application\Controller\Admin\ListUser::class,
            'login'                                => \OxidEsales\EshopCommunity\Application\Controller\Admin\LoginController::class,
            'manufacturer'                         => \OxidEsales\EshopCommunity\Application\Controller\Admin\ManufacturerController::class,
            'manufacturer_list'                    => \OxidEsales\EshopCommunity\Application\Controller\Admin\ManufacturerList::class,
            'manufacturer_main'                    => \OxidEsales\EshopCommunity\Application\Controller\Admin\ManufacturerMain::class,
            'manufacturer_main_ajax'               => \OxidEsales\EshopCommunity\Application\Controller\Admin\ManufacturerMainAjax::class,
            'manufacturer_seo'                     => \OxidEsales\EshopCommunity\Application\Controller\Admin\ManufacturerSeo::class,
            'module_config'                        => \OxidEsales\EshopCommunity\Application\Controller\Admin\ModuleConfiguration::class,
            'module_list'                          => \OxidEsales\EshopCommunity\Application\Controller\Admin\ModuleList::class,
            'module_main'                          => \OxidEsales\EshopCommunity\Application\Controller\Admin\ModuleMain::class,
            'module_sortlist'                      => \OxidEsales\EshopCommunity\Application\Controller\Admin\ModuleSortList::class,
            'navigation'                           => \OxidEsales\EshopCommunity\Application\Controller\Admin\NavigationController::class,
            'news_list'                            => \OxidEsales\EshopCommunity\Application\Controller\Admin\NewsList::class,
            'news_main'                            => \OxidEsales\EshopCommunity\Application\Controller\Admin\NewsMain::class,
            'news_main_ajax'                       => \OxidEsales\EshopCommunity\Application\Controller\Admin\NewsMainAjax::class,
            'news_text'                            => \OxidEsales\EshopCommunity\Application\Controller\Admin\NewsText::class,
            'newsletter_list'                      => \OxidEsales\EshopCommunity\Application\Controller\Admin\NewsletterList::class,
            'newsletter_main'                      => \OxidEsales\EshopCommunity\Application\Controller\Admin\NewsletterMain::class,
            'newsletter_plain'                     => \OxidEsales\EshopCommunity\Application\Controller\Admin\NewsletterPlain::class,
            'newsletter_preview'                   => \OxidEsales\EshopCommunity\Application\Controller\Admin\NewsletterPreview::class,
            'newsletter_selection'                 => \OxidEsales\EshopCommunity\Application\Controller\Admin\NewsletterSelection::class,
            'newsletter_selection_ajax'            => \OxidEsales\EshopCommunity\Application\Controller\Admin\NewsletterSelectionAjax::class,
            'newsletter_send'                      => \OxidEsales\EshopCommunity\Application\Controller\Admin\NewsletterSend::class,
            'order_address'                        => \OxidEsales\EshopCommunity\Application\Controller\Admin\OrderAddress::class,
            'order_article'                        => \OxidEsales\EshopCommunity\Application\Controller\Admin\OrderArticle::class,
            'order_downloads'                      => \OxidEsales\EshopCommunity\Application\Controller\Admin\OrderDownloads::class,
            'order_main'                           => \OxidEsales\EshopCommunity\Application\Controller\Admin\OrderMain::class,
            'order_overview'                       => \OxidEsales\EshopCommunity\Application\Controller\Admin\OrderOverview::class,
            'order_remark'                         => \OxidEsales\EshopCommunity\Application\Controller\Admin\OrderRemark::class,
            'oxnavigationtree'                     => \OxidEsales\EshopCommunity\Application\Controller\Admin\NavigationTree::class,
            'payment_country'                      => \OxidEsales\EshopCommunity\Application\Controller\Admin\PaymentCountry::class,
            'payment_country_ajax'                 => \OxidEsales\EshopCommunity\Application\Controller\Admin\PaymentCountryAjax::class,
            'payment_list'                         => \OxidEsales\EshopCommunity\Application\Controller\Admin\PaymentList::class,
            'payment_main'                         => \OxidEsales\EshopCommunity\Application\Controller\Admin\PaymentMain::class,
            'payment_main_ajax'                    => \OxidEsales\EshopCommunity\Application\Controller\Admin\PaymentMainAjax::class,
            'payment_rdfa'                         => \OxidEsales\EshopCommunity\Application\Controller\Admin\PaymentRdfa::class,
            'pricealarm_list'                      => \OxidEsales\EshopCommunity\Application\Controller\Admin\PriceAlarmList::class,
            'pricealarm_mail'                      => \OxidEsales\EshopCommunity\Application\Controller\Admin\PriceAlarmMail::class,
            'pricealarm_main'                      => \OxidEsales\EshopCommunity\Application\Controller\Admin\PriceAlarmMain::class,
            'pricealarm_send'                      => \OxidEsales\EshopCommunity\Application\Controller\Admin\PriceAlarmSend::class,
            'selectlist'                           => \OxidEsales\EshopCommunity\Application\Controller\Admin\SelectListController::class,
            'selectlist_list'                      => \OxidEsales\EshopCommunity\Application\Controller\Admin\SelectListList::class,
            'selectlist_main'                      => \OxidEsales\EshopCommunity\Application\Controller\Admin\SelectListMain::class,
            'selectlist_main_ajax'                 => \OxidEsales\EshopCommunity\Application\Controller\Admin\SelectListMainAjax::class,
            'selectlist_order_ajax'                => \OxidEsales\EshopCommunity\Application\Controller\Admin\SelectListOrderAjax::class,
            'shop'                                 => \OxidEsales\EshopCommunity\Application\Controller\Admin\ShopController::class,
            'shop_default_category_ajax'           => \OxidEsales\EshopCommunity\Application\Controller\Admin\ShopDefaultCategoryAjax::class,
            'shop_license'                         => \OxidEsales\EshopCommunity\Application\Controller\Admin\ShopLicense::class,
            'shop_list'                            => \OxidEsales\EshopCommunity\Application\Controller\Admin\ShopList::class,
            'shop_main'                            => \OxidEsales\EshopCommunity\Application\Controller\Admin\ShopMain::class,
            'shop_performance'                     => \OxidEsales\EshopCommunity\Application\Controller\Admin\ShopPerformance::class,
            'shop_rdfa'                            => \OxidEsales\EshopCommunity\Application\Controller\Admin\ShopRdfa::class,
            'shop_seo'                             => \OxidEsales\EshopCommunity\Application\Controller\Admin\ShopSeo::class,
            'shop_system'                          => \OxidEsales\EshopCommunity\Application\Controller\Admin\ShopSystem::class,
            'sysreq'                               => \OxidEsales\EshopCommunity\Application\Controller\Admin\SystemRequirements::class,
            'sysreq_list'                          => \OxidEsales\EshopCommunity\Application\Controller\Admin\SystemRequirementsList::class,
            'sysreq_main'                          => \OxidEsales\EshopCommunity\Application\Controller\Admin\SystemRequirementsMain::class,
            'systeminfo'                           => \OxidEsales\EshopCommunity\Application\Controller\Admin\SystemInfoController::class,
            'theme_config'                         => \OxidEsales\EshopCommunity\Application\Controller\Admin\ThemeConfiguration::class,
            'theme_list'                           => \OxidEsales\EshopCommunity\Application\Controller\Admin\ThemeList::class,
            'theme_main'                           => \OxidEsales\EshopCommunity\Application\Controller\Admin\ThemeMain::class,
            'tools'                                => \OxidEsales\EshopCommunity\Application\Controller\Admin\ToolsController::class,
            'tools_list'                           => \OxidEsales\EshopCommunity\Application\Controller\Admin\ToolsList::class,
            'tools_main'                           => \OxidEsales\EshopCommunity\Application\Controller\Admin\ToolsMain::class,
            'user_address'                         => \OxidEsales\EshopCommunity\Application\Controller\Admin\UserAddress::class,
            'user_article'                         => \OxidEsales\EshopCommunity\Application\Controller\Admin\UserArticle::class,
            'user_extend'                          => \OxidEsales\EshopCommunity\Application\Controller\Admin\UserExtend::class,
            'user_main'                            => \OxidEsales\EshopCommunity\Application\Controller\Admin\UserMain::class,
            'user_main_ajax'                       => \OxidEsales\EshopCommunity\Application\Controller\Admin\UserMainAjax::class,
            'user_overview'                        => \OxidEsales\EshopCommunity\Application\Controller\Admin\UserOverview::class,
            'user_payment'                         => \OxidEsales\EshopCommunity\Application\Controller\Admin\UserPayment::class,
            'user_remark'                          => \OxidEsales\EshopCommunity\Application\Controller\Admin\UserRemark::class,
            'usergroup'                            => \OxidEsales\EshopCommunity\Application\Controller\Admin\UserGroupController::class,
            'usergroup_list'                       => \OxidEsales\EshopCommunity\Application\Controller\Admin\UserGroupList::class,
            'usergroup_main'                       => \OxidEsales\EshopCommunity\Application\Controller\Admin\UserGroupMain::class,
            'usergroup_main_ajax'                  => \OxidEsales\EshopCommunity\Application\Controller\Admin\UserGroupMainAjax::class,
            'vendor'                               => \OxidEsales\EshopCommunity\Application\Controller\Admin\VendorController::class,
            'vendor_list'                          => \OxidEsales\EshopCommunity\Application\Controller\Admin\VendorList::class,
            'actions_article_ajax'                 => \OxidEsales\EshopCommunity\Application\Controller\Admin\ActionsArticleAjax::class,
            'actions_groups_ajax'                  => \OxidEsales\EshopCommunity\Application\Controller\Admin\ActionsGroupsAjax::class,
            'actions_list'                         => \OxidEsales\EshopCommunity\Application\Controller\Admin\ActionsList::class,
            'actions_main'                         => \OxidEsales\EshopCommunity\Application\Controller\Admin\ActionsMain::class,
            'actions_main_ajax'                    => \OxidEsales\EshopCommunity\Application\Controller\Admin\ActionsMainAjax::class,
            'actions_order_ajax'                   => \OxidEsales\EshopCommunity\Application\Controller\Admin\ActionsOrderAjax::class,
            'admin_content'                        => \OxidEsales\EshopCommunity\Application\Controller\Admin\AdminContent::class,
            'admin_links'                          => \OxidEsales\EshopCommunity\Application\Controller\Admin\AdminLinks::class,
            'admin_news'                           => \OxidEsales\EshopCommunity\Application\Controller\Admin\AdminNews::class,
            'admin_newsletter'                     => \OxidEsales\EshopCommunity\Application\Controller\Admin\AdminNewsletter::class,
            'admin_order'                          => \OxidEsales\EshopCommunity\Application\Controller\Admin\AdminOrder::class,
            'admin_payment'                        => \OxidEsales\EshopCommunity\Application\Controller\Admin\AdminPayment::class,
            'admin_pricealarm'                     => \OxidEsales\EshopCommunity\Application\Controller\Admin\AdminPriceAlarm::class,
            'admin_start'                          => \OxidEsales\EshopCommunity\Application\Controller\Admin\AdminStart::class,
            'admin_user'                           => \OxidEsales\EshopCommunity\Application\Controller\Admin\AdminUser::class,
            'admin_wrapping'                       => \OxidEsales\EshopCommunity\Application\Controller\Admin\AdminWrapping::class,
            'adminlinks_list'                      => \OxidEsales\EshopCommunity\Application\Controller\Admin\AdminlinksList::class,
            'adminlinks_main'                      => \OxidEsales\EshopCommunity\Application\Controller\Admin\AdminlinksMain::class,
            'article'                              => \OxidEsales\EshopCommunity\Application\Controller\Admin\ArticleController::class,
            'article_accessories_ajax'             => \OxidEsales\EshopCommunity\Application\Controller\Admin\ArticleAccessoriesAjax::class,
            'article_attribute'                    => \OxidEsales\EshopCommunity\Application\Controller\Admin\ArticleAttribute::class,
            'article_attribute_ajax'               => \OxidEsales\EshopCommunity\Application\Controller\Admin\ArticleAttributeAjax::class,
            'article_bundle_ajax'                  => \OxidEsales\EshopCommunity\Application\Controller\Admin\ArticleBundleAjax::class,
            'article_crossselling'                 => \OxidEsales\EshopCommunity\Application\Controller\Admin\ArticleCrossselling::class,
            'article_crossselling_ajax'            => \OxidEsales\EshopCommunity\Application\Controller\Admin\ArticleCrosssellingAjax::class,
            'article_extend'                       => \OxidEsales\EshopCommunity\Application\Controller\Admin\ArticleExtend::class,
            'article_extend_ajax'                  => \OxidEsales\EshopCommunity\Application\Controller\Admin\ArticleExtendAjax::class,
            'article_files'                        => \OxidEsales\EshopCommunity\Application\Controller\Admin\ArticleFiles::class,
            'article_main'                         => \OxidEsales\EshopCommunity\Application\Controller\Admin\ArticleMain::class,
            'article_overview'                     => \OxidEsales\EshopCommunity\Application\Controller\Admin\ArticleOverview::class,
            'article_pictures'                     => \OxidEsales\EshopCommunity\Application\Controller\Admin\ArticlePictures::class,
            'article_review'                       => \OxidEsales\EshopCommunity\Application\Controller\Admin\ArticleReview::class,
            'article_selection_ajax'               => \OxidEsales\EshopCommunity\Application\Controller\Admin\ArticleSelectionAjax::class,
            'article_seo'                          => \OxidEsales\EshopCommunity\Application\Controller\Admin\ArticleSeo::class,
            'article_stock'                        => \OxidEsales\EshopCommunity\Application\Controller\Admin\ArticleStock::class,
            'article_userdef'                      => \OxidEsales\EshopCommunity\Application\Controller\Admin\ArticleUserdef::class,
            'article_variant'                      => \OxidEsales\EshopCommunity\Application\Controller\Admin\ArticleVariant::class,
            'attribute'                            => \OxidEsales\EshopCommunity\Application\Controller\Admin\AttributeController::class,
            'attribute_category'                   => \OxidEsales\EshopCommunity\Application\Controller\Admin\AttributeCategory::class,
            'attribute_category_ajax'              => \OxidEsales\EshopCommunity\Application\Controller\Admin\AttributeCategoryAjax::class,
            'attribute_list'                       => \OxidEsales\EshopCommunity\Application\Controller\Admin\AttributeList::class,
            'attribute_main'                       => \OxidEsales\EshopCommunity\Application\Controller\Admin\AttributeMain::class,
            'attribute_main_ajax'                  => \OxidEsales\EshopCommunity\Application\Controller\Admin\AttributeMainAjax::class,
            'attribute_order_ajax'                 => \OxidEsales\EshopCommunity\Application\Controller\Admin\AttributeOrderAjax::class,
            'category'                             => \OxidEsales\EshopCommunity\Application\Controller\Admin\CategoryController::class,
            'category_list'                        => \OxidEsales\EshopCommunity\Application\Controller\Admin\CategoryList::class,
            'category_main'                        => \OxidEsales\EshopCommunity\Application\Controller\Admin\CategoryMain::class,
            'category_main_ajax'                   => \OxidEsales\EshopCommunity\Application\Controller\Admin\CategoryMainAjax::class,
            'category_order'                       => \OxidEsales\EshopCommunity\Application\Controller\Admin\CategoryOrder::class,
            'category_order_ajax'                  => \OxidEsales\EshopCommunity\Application\Controller\Admin\CategoryOrderAjax::class,
            'category_pictures'                    => \OxidEsales\EshopCommunity\Application\Controller\Admin\CategoryPictures::class,
            'category_seo'                         => \OxidEsales\EshopCommunity\Application\Controller\Admin\CategorySeo::class,
            'category_text'                        => \OxidEsales\EshopCommunity\Application\Controller\Admin\CategoryText::class,
            'category_update'                      => \OxidEsales\EshopCommunity\Application\Controller\Admin\CategoryUpdate::class,
            'content_list'                         => \OxidEsales\EshopCommunity\Application\Controller\Admin\ContentList::class,
            'content_main'                         => \OxidEsales\EshopCommunity\Application\Controller\Admin\ContentMain::class,
            'content_seo'                          => \OxidEsales\EshopCommunity\Application\Controller\Admin\ContentSeo::class,
            'country'                              => \OxidEsales\EshopCommunity\Application\Controller\Admin\CountryController::class,
            'country_list'                         => \OxidEsales\EshopCommunity\Application\Controller\Admin\CountryList::class,
            'country_main'                         => \OxidEsales\EshopCommunity\Application\Controller\Admin\CountryMain::class,
            'delivery'                             => \OxidEsales\EshopCommunity\Application\Controller\Admin\DeliveryController::class,
            'delivery_articles'                    => \OxidEsales\EshopCommunity\Application\Controller\Admin\DeliveryArticles::class,
            'delivery_articles_ajax'               => \OxidEsales\EshopCommunity\Application\Controller\Admin\DeliveryArticlesAjax::class,
            'delivery_categories_ajax'             => \OxidEsales\EshopCommunity\Application\Controller\Admin\DeliveryCategoriesAjax::class,
            'delivery_groups_ajax'                 => \OxidEsales\EshopCommunity\Application\Controller\Admin\DeliveryGroupsAjax::class,
            'delivery_list'                        => \OxidEsales\EshopCommunity\Application\Controller\Admin\DeliveryList::class,
            'delivery_main'                        => \OxidEsales\EshopCommunity\Application\Controller\Admin\DeliveryMain::class,
            'delivery_main_ajax'                   => \OxidEsales\EshopCommunity\Application\Controller\Admin\DeliveryMainAjax::class,
            'delivery_users'                       => \OxidEsales\EshopCommunity\Application\Controller\Admin\DeliveryUsers::class,
            'delivery_users_ajax'                  => \OxidEsales\EshopCommunity\Application\Controller\Admin\DeliveryUsersAjax::class,
            'deliveryset'                          => \OxidEsales\EshopCommunity\Application\Controller\Admin\DeliverySetController::class,
            'deliveryset_country_ajax'             => \OxidEsales\EshopCommunity\Application\Controller\Admin\DeliverySetCountryAjax::class,
            'deliveryset_groups_ajax'              => \OxidEsales\EshopCommunity\Application\Controller\Admin\DeliverySetGroupsAjax::class,
            'deliveryset_list'                     => \OxidEsales\EshopCommunity\Application\Controller\Admin\DeliverySetList::class,
            'deliveryset_main'                     => \OxidEsales\EshopCommunity\Application\Controller\Admin\DeliverySetMain::class,
            'deliveryset_main_ajax'                => \OxidEsales\EshopCommunity\Application\Controller\Admin\DeliverySetMainAjax::class,
            'deliveryset_payment'                  => \OxidEsales\EshopCommunity\Application\Controller\Admin\DeliverySetPayment::class,
            'deliveryset_payment_ajax'             => \OxidEsales\EshopCommunity\Application\Controller\Admin\DeliverySetPaymentAjax::class,
            'deliveryset_rdfa'                     => \OxidEsales\EshopCommunity\Application\Controller\Admin\DeliverySetRdfa::class,
            'deliveryset_users'                    => \OxidEsales\EshopCommunity\Application\Controller\Admin\DeliverySetUsers::class,
            'deliveryset_users_ajax'               => \OxidEsales\EshopCommunity\Application\Controller\Admin\DeliverySetUsersAjax::class,
            'diagnostics'                          => \OxidEsales\EshopCommunity\Application\Controller\Admin\DiagnosticsController::class,
            'diagnostics_list'                     => \OxidEsales\EshopCommunity\Application\Controller\Admin\DiagnosticsList::class,
            'diagnostics_main'                     => \OxidEsales\EshopCommunity\Application\Controller\Admin\DiagnosticsMain::class,
            'discount'                             => \OxidEsales\EshopCommunity\Application\Controller\Admin\DiscountController::class,
            'discount_articles'                    => \OxidEsales\EshopCommunity\Application\Controller\Admin\DiscountArticles::class,
            'discount_articles_ajax'               => \OxidEsales\EshopCommunity\Application\Controller\Admin\DiscountArticlesAjax::class,
            'discount_categories_ajax'             => \OxidEsales\EshopCommunity\Application\Controller\Admin\DiscountCategoriesAjax::class,
            'discount_groups_ajax'                 => \OxidEsales\EshopCommunity\Application\Controller\Admin\DiscountGroupsAjax::class,
            'discount_item_ajax'                   => \OxidEsales\EshopCommunity\Application\Controller\Admin\DiscountItemAjax::class,
            'discount_list'                        => \OxidEsales\EshopCommunity\Application\Controller\Admin\DiscountList::class,
            'discount_main'                        => \OxidEsales\EshopCommunity\Application\Controller\Admin\DiscountMain::class,
            'discount_main_ajax'                   => \OxidEsales\EshopCommunity\Application\Controller\Admin\DiscountMainAjax::class,
            'discount_users'                       => \OxidEsales\EshopCommunity\Application\Controller\Admin\DiscountUsers::class,
            'discount_users_ajax'                  => \OxidEsales\EshopCommunity\Application\Controller\Admin\DiscountUsersAjax::class,
            'dyn_econda'                           => \OxidEsales\EshopCommunity\Application\Controller\Admin\DynEconda::class,
            'content'                              => \OxidEsales\EshopCommunity\Application\Controller\ContentController::class,
            'links'                                => \OxidEsales\EshopCommunity\Application\Controller\LinksController::class,
            'news'                                 => \OxidEsales\EshopCommunity\Application\Controller\NewsController::class,
            'newsletter'                           => \OxidEsales\EshopCommunity\Application\Controller\NewsletterController::class,
            'pricealarm'                           => \OxidEsales\EshopCommunity\Application\Controller\PriceAlarmController::class,
            'account_noticelist'                   => \OxidEsales\EshopCommunity\Application\Controller\AccountNoticeListController::class,
            'oxuser'                               => \OxidEsales\Eshop\Application\Model\User::class,
        ];
    }

    /**
     * @inheritdoc
     */
    public function getNotOverridableMap()
    {
        return [
            // 'oxuser'                               => \OxidEsales\EshopCommunity\Application\Model\User::class,
            'oxbase'                              => \OxidEsales\EshopCommunity\Core\Model\BaseModel::class,
            'oxsysrequirements'                   => \OxidEsales\EshopCommunity\Core\SystemRequirements::class,
            'oxadminview'                         => AdminController::class,
            'oxadminlist'                         => AdminListController::class,
            'order_list'                          => \OxidEsales\EshopCommunity\Application\Controller\Admin\OrderList::class,
            'user_list'                           => \OxidEsales\EshopCommunity\Application\Controller\Admin\UserList::class,
            'oxadmindetails'                      => AdminDetailsController::class,
            'ajaxlistcomponent'                   => \OxidEsales\EshopCommunity\Application\Controller\Admin\ListComponentAjax::class,
            'article_list'                        => \OxidEsales\EshopCommunity\Application\Controller\Admin\ArticleList::class,
            'oxshopidcalculator'                  => \OxidEsales\EshopCommunity\Core\ShopIdCalculator::class,
            'details'                             => \OxidEsales\EshopCommunity\Application\Controller\ArticleDetailsController::class,
            'oxubase'                             => FrontendController::class,
            'alist'                               => \OxidEsales\EshopCommunity\Application\Controller\ArticleListController::class,
            'user'                                => \OxidEsales\EshopCommunity\Application\Controller\UserController::class,
            'account'                             => \OxidEsales\EshopCommunity\Application\Controller\AccountController::class,
            'basket'                              => \OxidEsales\EshopCommunity\Application\Controller\BasketController::class,
            'compare'                             => \OxidEsales\EshopCommunity\Application\Controller\CompareController::class,
            'order'                               => \OxidEsales\EshopCommunity\Application\Controller\OrderController::class,
            'payment'                             => \OxidEsales\EshopCommunity\Application\Controller\PaymentController::class,
            'recommlist'                          => \OxidEsales\EshopCommunity\Application\Controller\RecommListController::class,
            'rss'                                 => \OxidEsales\EshopCommunity\Application\Controller\RssController::class,
            'search'                              => \OxidEsales\EshopCommunity\Application\Controller\SearchController::class,
            'start'                               => \OxidEsales\EshopCommunity\Application\Controller\StartController::class,
            'thankyou'                            => \OxidEsales\EshopCommunity\Application\Controller\ThankYouController::class,
            'wishlist'                            => \OxidEsales\EshopCommunity\Application\Controller\WishListController::class,
            'wrapping'                            => \OxidEsales\EshopCommunity\Application\Controller\WrappingController::class,
            'oxshopcontrol'                       => \OxidEsales\EshopCommunity\Core\ShopControl::class,
            'oxview'                              => BaseController::class,
            'oxi18n'                              => MultiLanguageModel::class,
            'oxsupercfg'                          => \OxidEsales\EshopCommunity\Core\Base::class,
            'oxutilsobject'                       => \OxidEsales\EshopCommunity\Core\UtilsObject::class,
            'oxdb'                                => DatabaseProvider::class,
            'oxconnectionexception'               => \OxidEsales\EshopCommunity\Core\Exception\ConnectionException::class,
            'oxdynimggenerator'                   => \OxidEsales\EshopCommunity\Core\DynamicImageGenerator::class,
            'oxexceptiontodisplay'                => \OxidEsales\EshopCommunity\Core\Exception\ExceptionToDisplay::class,
            'oxfield'                             => \OxidEsales\EshopCommunity\Core\Field::class,
            'oxlist'                              => ListModel::class,
            'oxseoencoder'                        => \OxidEsales\EshopCommunity\Core\SeoEncoder::class,
            'oxstdclass'                          => \OxidEsales\EshopCommunity\Core\StandardClass::class,
            'oxsystemcomponentexception'          => \OxidEsales\EshopCommunity\Core\Exception\SystemComponentException::class,
            'oxconfigfile'                        => \OxidEsales\EshopCommunity\Core\ConfigFile::class,
            'oxregistry'                          => \OxidEsales\EshopCommunity\Core\Registry::class,
            'oxstart'                             => \OxidEsales\EshopCommunity\Application\Controller\OxidStartController::class,
            'dyn_interface'                       => \OxidEsales\EshopCommunity\Application\Controller\Admin\DynamicInterface::class,
            'dyn_screen'                          => \OxidEsales\EshopCommunity\Application\Controller\Admin\DynamicScreenController::class,
            'dynexportbase'                       => \OxidEsales\EshopCommunity\Application\Controller\Admin\DynamicExportBaseController::class,
            'genimport_main'                      => \OxidEsales\EshopCommunity\Application\Controller\Admin\GenericImportMain::class,
            'object_seo'                          => \OxidEsales\EshopCommunity\Application\Controller\Admin\ObjectSeo::class,
            'shop_config'                         => \OxidEsales\EshopCommunity\Application\Controller\Admin\ShopConfiguration::class,
            'oxvoucherexception'                  => \OxidEsales\EshopCommunity\Core\Exception\VoucherException::class,
            'oxuserexception'                     => \OxidEsales\EshopCommunity\Core\Exception\UserException::class,
            'oxshopexception'                     => \OxidEsales\EshopCommunity\Core\Exception\ShopException::class,
            'oxoutofstockexception'               => \OxidEsales\EshopCommunity\Core\Exception\OutOfStockException::class,
            'oxobjectexception'                   => \OxidEsales\EshopCommunity\Core\Exception\ObjectException::class,
            'oxnoarticleexception'                => \OxidEsales\EshopCommunity\Core\Exception\NoArticleException::class,
            'oxinputexception'                    => \OxidEsales\EshopCommunity\Core\Exception\InputException::class,
            'oxfileexception'                     => \OxidEsales\EshopCommunity\Core\Exception\FileException::class,
            'oxexceptionhandler'                  => \OxidEsales\EshopCommunity\Core\Exception\ExceptionHandler::class,
            'oxexception'                         => \OxidEsales\EshopCommunity\Core\Exception\StandardException::class,
            'oxcookieexception'                   => \OxidEsales\EshopCommunity\Core\Exception\CookieException::class,
            'oxarticleinputexception'             => \OxidEsales\EshopCommunity\Core\Exception\ArticleInputException::class,
            'oxarticleexception'                  => \OxidEsales\EshopCommunity\Core\Exception\ArticleException::class,
            'oxlanguageexception'                 => \OxidEsales\EshopCommunity\Core\Exception\LanguageException::class,
            'oxmodule'                            => \OxidEsales\EshopCommunity\Core\Module::class,
            'oxmodulecache'                       => \OxidEsales\EshopCommunity\Core\ModuleCache::class,
            'oxmodulefilesvalidator'              => \OxidEsales\EshopCommunity\Core\ModuleFilesValidator::class,
            'oxonlinemoduleversionnotifier'       => \OxidEsales\EshopCommunity\Core\OnlineModuleVersionNotifier::class,
            'oxmodulelist'                        => \OxidEsales\EshopCommunity\Core\ModuleList::class,
            'oxmodulemetadatavalidator'           => \OxidEsales\EshopCommunity\Core\ModuleMetadataValidator::class,
            'oxcurl'                              => \OxidEsales\EshopCommunity\Core\Curl::class,
            'oxonlineserveremailbuilder'          => \OxidEsales\EshopCommunity\Core\OnlineServerEmailBuilder::class,
            'oxonlinelicensecheckrequest'         => \OxidEsales\EshopCommunity\Core\OnlineLicenseCheckRequest::class,
            'oxonlinerequest'                     => \OxidEsales\EshopCommunity\Core\OnlineRequest::class,
            'oxonlinelicensecheck'                => \OxidEsales\EshopCommunity\Core\OnlineLicenseCheck::class,
            'oxonlinemoduleversionnotifiercaller' => \OxidEsales\EshopCommunity\Core\OnlineModuleVersionNotifierCaller::class,
            'oxonlinemodulesnotifierrequest'      => \OxidEsales\EshopCommunity\Core\OnlineModulesNotifierRequest::class,
            'oxconfig'                            => \OxidEsales\EshopCommunity\Core\Config::class,
            'oxlang'                              => \OxidEsales\EshopCommunity\Core\Language::class,
            'oxcompanyvatinvalidator'             => \OxidEsales\EshopCommunity\Core\CompanyVatInValidator::class,
            'oxcompanyvatincountrychecker'        => \OxidEsales\EshopCommunity\Core\CompanyVatInCountryChecker::class,
            'oxonlinevatidcheck'                  => \OxidEsales\EshopCommunity\Core\OnlineVatIdCheck::class,
            'oxserversmanager'                    => \OxidEsales\EshopCommunity\Core\ServersManager::class,
            'oxserverchecker'                     => \OxidEsales\EshopCommunity\Core\ServerChecker::class,
            'oxutilsserver'                       => \OxidEsales\EshopCommunity\Core\UtilsServer::class,
            'oxutilsdate'                         => \OxidEsales\EshopCommunity\Core\UtilsDate::class,
            'oxoutput'                            => \OxidEsales\EshopCommunity\Core\Output::class,
            'oxutilspic'                          => \OxidEsales\EshopCommunity\Core\UtilsPic::class,
            'oxutils'                             => \OxidEsales\EshopCommunity\Core\Utils::class,
            'oxprice'                             => \OxidEsales\EshopCommunity\Core\Price::class,
            'oxsimplexml'                         => \OxidEsales\EshopCommunity\Core\SimpleXml::class,
            'oxopensslfunctionalitychecker'       => \OxidEsales\EshopCommunity\Core\OpenSSLFunctionalityChecker::class,
            'oxstrmb'                             => \OxidEsales\EshopCommunity\Core\StrMb::class,
            'oxstr'                               => \OxidEsales\EshopCommunity\Core\Str::class,
            'oxsession'                           => \OxidEsales\EshopCommunity\Core\Session::class,
            'oxtheme'                             => \OxidEsales\EshopCommunity\Core\Theme::class,
            'oxpricelist'                         => \OxidEsales\EshopCommunity\Core\PriceList::class,
            'oxdisplayerror'                      => \OxidEsales\EshopCommunity\Core\DisplayError::class,
            'oxiconfigurable'                     => \OxidEsales\EshopCommunity\Core\Contract\IConfigurable::class,
            'oxicountryaware'                     => \OxidEsales\EshopCommunity\Core\Contract\ICountryAware::class,
            'oxidisplayerror'                     => \OxidEsales\EshopCommunity\Core\Contract\IDisplayError::class,
            'oximodulevalidator'                  => \OxidEsales\EshopCommunity\Core\Contract\IModuleValidator::class,
            'oxiselectlist'                       => \OxidEsales\EshopCommunity\Core\Contract\ISelectList::class,
            'oxiurl'                              => \OxidEsales\EshopCommunity\Core\Contract\IUrl::class,
            'oxactionlist'                        => \OxidEsales\EshopCommunity\Application\Model\ActionList::class,
            'oxactions'                           => \OxidEsales\EshopCommunity\Application\Model\Actions::class,
            'oxaddress'                           => \OxidEsales\EshopCommunity\Application\Model\Address::class,
            'oxamountpricelist'                   => \OxidEsales\EshopCommunity\Application\Model\AmountPriceList::class,
            'oxarticlelist'                       => \OxidEsales\EshopCommunity\Application\Model\ArticleList::class,
            'oxattribute'                         => \OxidEsales\EshopCommunity\Application\Model\Attribute::class,
            'oxattributelist'                     => \OxidEsales\EshopCommunity\Application\Model\AttributeList::class,
            'oxbasket'                            => \OxidEsales\EshopCommunity\Application\Model\Basket::class,
            'oxbasketcontentmarkgenerator'        => \OxidEsales\EshopCommunity\Application\Model\BasketContentMarkGenerator::class,
            'oxbasketitem'                        => \OxidEsales\EshopCommunity\Application\Model\BasketItem::class,
            'oxbasketreservation'                 => \OxidEsales\EshopCommunity\Application\Model\BasketReservation::class,
            'oxcategory'                          => \OxidEsales\EshopCommunity\Application\Model\Category::class,
            'oxcategorylist'                      => \OxidEsales\EshopCommunity\Application\Model\CategoryList::class,
            'oxcompanyvatin'                      => \OxidEsales\EshopCommunity\Application\Model\CompanyVatIn::class,
            'oxcontent'                           => \OxidEsales\EshopCommunity\Application\Model\Content::class,
            'oxcontentlist'                       => \OxidEsales\EshopCommunity\Application\Model\ContentList::class,
            'oxcountry'                           => \OxidEsales\EshopCommunity\Application\Model\Country::class,
            'oxcountrylist'                       => \OxidEsales\EshopCommunity\Application\Model\CountryList::class,
            'oxdelivery'                          => \OxidEsales\EshopCommunity\Application\Model\Delivery::class,
            'oxdeliverylist'                      => \OxidEsales\EshopCommunity\Application\Model\DeliveryList::class,
            'oxdeliveryset'                       => \OxidEsales\EshopCommunity\Application\Model\DeliverySet::class,
            'oxdeliverysetlist'                   => \OxidEsales\EshopCommunity\Application\Model\DeliverySetList::class,
            'oxdiagnostics'                       => \OxidEsales\EshopCommunity\Application\Model\Diagnostics::class,
            'oxdiagnosticsoutput'                 => \OxidEsales\EshopCommunity\Application\Model\DiagnosticsOutput::class,
            'oxdiscount'                          => \OxidEsales\EshopCommunity\Application\Model\Discount::class,
            'oxdiscountlist'                      => \OxidEsales\EshopCommunity\Application\Model\DiscountList::class,
            'oxfile'                              => \OxidEsales\EshopCommunity\Application\Model\File::class,
            'oxfilechecker'                       => \OxidEsales\EshopCommunity\Application\Model\FileChecker::class,
            'oxfilecheckerresult'                 => \OxidEsales\EshopCommunity\Application\Model\FileCheckerResult::class,
            'oxfilecollector'                     => \OxidEsales\EshopCommunity\Application\Model\FileCollector::class,
            'oxgroups'                            => \OxidEsales\EshopCommunity\Application\Model\Groups::class,
            'oxlinks'                             => \OxidEsales\EshopCommunity\Application\Model\Links::class,
            'oxlistobject'                        => \OxidEsales\EshopCommunity\Application\Model\ListObject::class,
            'oxmaintenance'                       => \OxidEsales\EshopCommunity\Application\Model\Maintenance::class,
            'oxmanufacturer'                      => \OxidEsales\EshopCommunity\Application\Model\Manufacturer::class,
            'oxmanufacturerlist'                  => \OxidEsales\EshopCommunity\Application\Model\ManufacturerList::class,
            'oxmdvariant'                         => \OxidEsales\EshopCommunity\Application\Model\MdVariant::class,
            'oxmediaurl'                          => \OxidEsales\EshopCommunity\Application\Model\MediaUrl::class,
            'oxnews'                              => \OxidEsales\EshopCommunity\Application\Model\News::class,
            'oxnewsletter'                        => \OxidEsales\EshopCommunity\Application\Model\Newsletter::class,
            'oxnewslist'                          => \OxidEsales\EshopCommunity\Application\Model\NewsList::class,
            'oxnewssubscribed'                    => \OxidEsales\EshopCommunity\Application\Model\NewsSubscribed::class,
            'oxobject2category'                   => \OxidEsales\EshopCommunity\Application\Model\Object2Category::class,
            'oxobject2group'                      => \OxidEsales\EshopCommunity\Application\Model\Object2Group::class,
            'oxorder'                             => \OxidEsales\EshopCommunity\Application\Model\Order::class,
            'oxorderarticlelist'                  => \OxidEsales\EshopCommunity\Application\Model\OrderArticleList::class,
            'oxorderfile'                         => \OxidEsales\EshopCommunity\Application\Model\OrderFile::class,
            'oxorderfilelist'                     => \OxidEsales\EshopCommunity\Application\Model\OrderFileList::class,
            'oxpaymentgateway'                    => \OxidEsales\EshopCommunity\Application\Model\PaymentGateway::class,
            'oxpaymentlist'                       => \OxidEsales\EshopCommunity\Application\Model\PaymentList::class,
            'oxpricealarm'                        => \OxidEsales\EshopCommunity\Application\Model\PriceAlarm::class,
            'oxrating'                            => \OxidEsales\EshopCommunity\Application\Model\Rating::class,
            'oxrecommlist'                        => \OxidEsales\EshopCommunity\Application\Model\RecommendationList::class,
            'oxremark'                            => \OxidEsales\EshopCommunity\Application\Model\Remark::class,
            'oxrequiredaddressfields'             => \OxidEsales\EshopCommunity\Application\Model\RequiredAddressFields::class,
            'oxrequiredfieldsvalidator'           => \OxidEsales\EshopCommunity\Application\Model\RequiredFieldsValidator::class,
            'oxrequiredfieldvalidator'            => \OxidEsales\EshopCommunity\Application\Model\RequiredFieldValidator::class,
            'oxreview'                            => \OxidEsales\EshopCommunity\Application\Model\Review::class,
            'oxrssfeed'                           => \OxidEsales\EshopCommunity\Application\Model\RssFeed::class,
            'oxsearch'                            => \OxidEsales\EshopCommunity\Application\Model\Search::class,
            'oxselection'                         => \OxidEsales\EshopCommunity\Application\Model\Selection::class,
            'oxselectlist'                        => \OxidEsales\EshopCommunity\Application\Model\SelectList::class,
            'oxseoencoderarticle'                 => \OxidEsales\EshopCommunity\Application\Model\SeoEncoderArticle::class,
            'oxseoencodercategory'                => \OxidEsales\EshopCommunity\Application\Model\SeoEncoderCategory::class,
            'oxseoencodercontent'                 => \OxidEsales\EshopCommunity\Application\Model\SeoEncoderContent::class,
            'oxseoencodermanufacturer'            => \OxidEsales\EshopCommunity\Application\Model\SeoEncoderManufacturer::class,
            'oxseoencoderrecomm'                  => \OxidEsales\EshopCommunity\Application\Model\SeoEncoderRecomm::class,
            'oxseoencodervendor'                  => \OxidEsales\EshopCommunity\Application\Model\SeoEncoderVendor::class,
            'oxshop'                              => \OxidEsales\EshopCommunity\Application\Model\Shop::class,
            'oxshoplist'                          => \OxidEsales\EshopCommunity\Application\Model\ShopList::class,
            'oxshopviewvalidator'                 => \OxidEsales\EshopCommunity\Application\Model\ShopViewValidator::class,
            'oxsimplevariant'                     => \OxidEsales\EshopCommunity\Application\Model\SimpleVariant::class,
            'oxsimplevariantlist'                 => \OxidEsales\EshopCommunity\Application\Model\SimpleVariantList::class,
            'oxsmartyrenderer'                    => \OxidEsales\EshopCommunity\Application\Model\SmartyRenderer::class,
            'oxstate'                             => \OxidEsales\EshopCommunity\Application\Model\State::class,
            'oxuseraddresslist'                   => \OxidEsales\EshopCommunity\Application\Model\UserAddressList::class,
            'oxuserbasket'                        => \OxidEsales\EshopCommunity\Application\Model\UserBasket::class,
            'oxuserbasketitem'                    => \OxidEsales\EshopCommunity\Application\Model\UserBasketItem::class,
            'oxuserlist'                          => \OxidEsales\EshopCommunity\Application\Model\UserList::class,
            'oxuserpayment'                       => \OxidEsales\EshopCommunity\Application\Model\UserPayment::class,
            'oxvarianthandler'                    => \OxidEsales\EshopCommunity\Application\Model\VariantHandler::class,
            'oxvariantselectlist'                 => \OxidEsales\EshopCommunity\Application\Model\VariantSelectList::class,
            'oxvatselector'                       => \OxidEsales\EshopCommunity\Application\Model\VatSelector::class,
            'oxvendor'                            => \OxidEsales\EshopCommunity\Application\Model\Vendor::class,
            'oxvendorlist'                        => \OxidEsales\EshopCommunity\Application\Model\VendorList::class,
            'oxvoucher'                           => \OxidEsales\EshopCommunity\Application\Model\Voucher::class,
            'oxvoucherlist'                       => \OxidEsales\EshopCommunity\Application\Model\VoucherList::class,
            'oxvoucherserie'                      => \OxidEsales\EshopCommunity\Application\Model\VoucherSerie::class,
            'oxwrapping'                          => \OxidEsales\EshopCommunity\Application\Model\Wrapping::class,
            'oxarticle'                           => \OxidEsales\EshopCommunity\Application\Model\Article::class,
            'clearcookies'                        => \OxidEsales\EshopCommunity\Application\Controller\ClearCookiesController::class,
        ];
    }
}
