imports:
  - { resource: Api/services.yaml }
  - { resource: Cache/services.yaml }
  - { resource: Logger/services.yaml }
  - { resource: Templating/services.yaml }
  - { resource: Theme/services.yaml }
  - { resource: Console/services.yaml }
  - { resource: Module/services.yaml }
  - { resource: Event/services.yaml }
  - { resource: Database/services.yaml }
  - { resource: Form/services.yaml }
  - { resource: DIContainer/services.yaml }
  - { resource: Migration/services.yaml }
  - { resource: FileSystem/services.yaml }
  - { resource: SystemRequirements/services.yaml }
  - { resource: Request/services.yaml }
  - { resource: Session/services.yaml }
  - { resource: Html/services.yaml }
  - { resource: Mailing/services.yaml }
  - { resource: RateLimiter/services.yaml }
