services:
  _defaults:
    autowire: true

  OxidEsales\EshopCommunity\Internal\Framework\Theme\State\ThemeStateServiceInterface:
    class: OxidEsales\EshopCommunity\Internal\Framework\Theme\State\ThemeStateService
    public: true

  OxidEsales\EshopCommunity\Internal\Framework\Theme\State\CustomThemeProviderInterface:
    class: OxidEsales\EshopCommunity\Internal\Framework\Theme\State\CustomThemeProvider
    public: true

  OxidEsales\EshopCommunity\Internal\Framework\Theme\State\ThemeParentProviderInterface:
    class: OxidEsales\EshopCommunity\Internal\Framework\Theme\State\ThemeParentProvider
    public: true

  OxidEsales\EshopCommunity\Internal\Framework\Theme\State\ThemeMetaDataByIdProviderInterface:
    class: OxidEsales\EshopCommunity\Internal\Framework\Theme\State\ThemeMetaDataByIdProvider
    public: true

  OxidEsales\EshopCommunity\Internal\Framework\Theme\State\ThemeParentCompatibilityCheckerInterface:
    class: OxidEsales\EshopCommunity\Internal\Framework\Theme\State\ThemeParentCompatibilityChecker
    public: true
