services:
  _defaults:
    autowire: true

  OxidEsales\EshopCommunity\Internal\Framework\Theme\Setup\Service\ThemeActivationServiceInterface:
    class: OxidEsales\EshopCommunity\Internal\Framework\Theme\Setup\Service\ThemeActivationService

  OxidEsales\EshopCommunity\Internal\Framework\Theme\Setup\Service\ThemeParentCompatibilityCheckerInterface:
    class: OxidEsales\EshopCommunity\Internal\Framework\Theme\Setup\Service\ThemeParentCompatibilityChecker
