parameters:
  oxid_esales.rate_limiter.storefront.enabled: false
  oxid_esales.rate_limiter.storefront.limit: 100
  oxid_esales.rate_limiter.storefront.interval: '60 seconds'
  oxid_esales.rate_limiter.storefront.excluded_routes: []
  oxid_esales.rate_limiter.storefront.excluded_ips: []
