services:
  _defaults:
    autowire: true

  OxidEsales\EshopCommunity\Internal\Domain\Product\Media\Dao\ProductMediaDaoInterface:
    class: OxidEsales\EshopCommunity\Internal\Domain\Product\Media\Dao\ProductMediaDao
    public: true

  OxidEsales\EshopCommunity\Internal\Domain\Product\Media\Factory\ProductMediaFactoryInterface:
      class: OxidEsales\EshopCommunity\Internal\Domain\Product\Media\Factory\ProductMediaFactory

  OxidEsales\EshopCommunity\Internal\Domain\Product\Media\Service\ProductMediaServiceInterface:
    class: OxidEsales\EshopCommunity\Internal\Domain\Product\Media\Service\ProductMediaService
    public: true

  OxidEsales\EshopCommunity\Internal\Domain\Product\Media\Service\ProductMediaViewServiceInterface:
    class: OxidEsales\EshopCommunity\Internal\Domain\Product\Media\Service\ProductMediaViewService
    public: true

  OxidEsales\EshopCommunity\Internal\Domain\Product\Media\Service\CachedProductMediaViewService:
    decorates: OxidEsales\EshopCommunity\Internal\Domain\Product\Media\Service\ProductMediaViewServiceInterface

  OxidEsales\EshopCommunity\Internal\Domain\Product\Media\Service\ProductMediaImageSizesProviderInterface:
    class: OxidEsales\EshopCommunity\Internal\Domain\Product\Media\Service\ProductMediaImageSizesProvider

  OxidEsales\EshopCommunity\Internal\Domain\Product\Media\Factory\ProductMediaViewFactoryInterface:
    class: OxidEsales\EshopCommunity\Internal\Domain\Product\Media\Factory\ProductMediaViewFactory

  OxidEsales\EshopCommunity\Internal\Domain\Product\Media\Factory\FallbackMediaFactoryInterface:
    class: OxidEsales\EshopCommunity\Internal\Domain\Product\Media\Factory\FallbackMediaFactory

  OxidEsales\EshopCommunity\Internal\Domain\Product\Media\Cache\ProductMediaViewCacheInterface:
    class: OxidEsales\EshopCommunity\Internal\Domain\Product\Media\Cache\ProductMediaViewCache
    arguments:
      $lifetimeSeconds: '%oxid_esales.product.media.view_cache.lifetime_seconds%'

  oxid_esales.product.media.invalidate_product_media_view_cache_event_subscriber:
    class: OxidEsales\EshopCommunity\Internal\Domain\Product\Media\Cache\InvalidateProductMediaViewCacheEventSubscriber
    tags:
      - { name: kernel.event_subscriber }

  OxidEsales\EshopCommunity\Internal\Domain\Product\Media\Service\ProductVariantMediaServiceInterface:
    class: OxidEsales\EshopCommunity\Internal\Domain\Product\Media\Service\ProductVariantMediaService
    public: true

  OxidEsales\EshopCommunity\Internal\Domain\Product\Media\Service\ProductMediaUploadProcessorInterface:
    class: OxidEsales\EshopCommunity\Internal\Domain\Product\Media\Service\ProductMediaUploadProcessor
    arguments:
      $mediaConstraintValidator: '@OxidEsales\EshopCommunity\Internal\Domain\Product\Media\Validator\ProductMediaValidator'
      $mediaUploader: '@oxid_esales.product.media.media_uploader'
    public: true

  OxidEsales\EshopCommunity\Internal\Domain\Product\Media\Service\ProductMediaPathResolverInterface:
    class: OxidEsales\EshopCommunity\Internal\Domain\Product\Media\Service\ProductMediaPathResolver

  OxidEsales\EshopCommunity\Internal\Domain\Product\Media\DataMapper\DataMapperInterface:
    class: OxidEsales\EshopCommunity\Internal\Domain\Product\Media\DataMapper\DataMapper

  oxid_esales.product.media.media_uploader:
    class: OxidEsales\EshopCommunity\Internal\Domain\Media\MediaUploader

  oxid_esales.product.media.constraint_validator.upload_validity:
    class: OxidEsales\EshopCommunity\Internal\Domain\Media\Validator\UploadValidityConstraintValidator
    tags:
      - { name: oxid.product_media.constraint_validator }

  oxid_esales.product.media.constraint_validator.size:
    class: OxidEsales\EshopCommunity\Internal\Domain\Media\Validator\FileSizeConstraintValidator
    arguments:
      $minSizeKb: '%oxid_esales.product.media.file.min_size_kb%'
      $maxSizeKb: '%oxid_esales.product.media.file.max_size_kb%'
    tags:
      - { name: oxid.product_media.constraint_validator }

  oxid_esales.product.media.constraint_validator.mime_type:
    class: OxidEsales\EshopCommunity\Internal\Domain\Media\Validator\MimeTypeConstraintValidator
    arguments:
      $baseTypePrefix: 'image/'
      $mimeTypeGuesser: "@oxid_esales.symfony.mime_types"
    tags:
      - { name: oxid.product_media.constraint_validator }

  oxid_esales.product.media.constraint_validator.file_extension:
    class: OxidEsales\EshopCommunity\Internal\Domain\Media\Validator\FileExtensionConstraintValidator
    arguments:
      $mimeTypeGuesser: "@oxid_esales.symfony.mime_types"
    tags:
      - { name: oxid.product_media.constraint_validator }

  OxidEsales\EshopCommunity\Internal\Domain\Product\Media\Validator\ProductMediaValidator:
    arguments:
      $validators: !tagged_iterator oxid.product_media.constraint_validator

  OxidEsales\EshopCommunity\Application\Controller\Admin\ArticleImageAlt:
    arguments:
      $request: '@Symfony\Component\HttpFoundation\Request'
      $thumbnailSize: '%oxid_esales.theme.admin.media.image_grid_size%'
    tags:
      - { name: 'oxid.view_controller', controller_key: 'article_image_alt' }
    public: true
