services:
  _defaults:
    autowire: true

  OxidEsales\EshopCommunity\Internal\Domain\Product\Media\Dao\ProductMediaDaoInterface:
    class: OxidEsales\EshopCommunity\Internal\Domain\Product\Media\Dao\ProductMediaDao
    public: true

  OxidEsales\EshopCommunity\Internal\Domain\Product\Media\Factory\ProductMediaFactoryInterface:
      class: OxidEsales\EshopCommunity\Internal\Domain\Product\Media\Factory\ProductMediaFactory

  OxidEsales\EshopCommunity\Internal\Domain\Product\Media\Service\ProductMediaServiceInterface:
    class: OxidEsales\EshopCommunity\Internal\Domain\Product\Media\Service\ProductMediaService
    public: true

  OxidEsales\EshopCommunity\Internal\Domain\Product\Media\Service\ProductMediaViewServiceInterface:
    class: OxidEsales\EshopCommunity\Internal\Domain\Product\Media\Service\ProductMediaViewService
    public: true

  OxidEsales\EshopCommunity\Internal\Domain\Product\Media\Service\ProductVariantMediaServiceInterface:
    class: OxidEsales\EshopCommunity\Internal\Domain\Product\Media\Service\ProductVariantMediaService
    public: true

  OxidEsales\EshopCommunity\Internal\Domain\Product\Media\Service\ProductMediaUploadProcessorInterface:
    class: OxidEsales\EshopCommunity\Internal\Domain\Product\Media\Service\ProductMediaUploadProcessor
    arguments:
      $mediaConstraintValidator: '@OxidEsales\EshopCommunity\Internal\Domain\Product\Media\Validator\ProductMediaValidator'
      $mediaUploader: '@oxid_esales.product.media.media_uploader'
    public: true

  OxidEsales\EshopCommunity\Internal\Domain\Product\Media\Service\ProductMediaPathResolverInterface:
    class: OxidEsales\EshopCommunity\Internal\Domain\Product\Media\Service\ProductMediaPathResolver

  OxidEsales\EshopCommunity\Internal\Domain\Product\Media\DataMapper\DataMapperInterface:
    class: OxidEsales\EshopCommunity\Internal\Domain\Product\Media\DataMapper\DataMapper

  oxid_esales.product.media.media_uploader:
    class: OxidEsales\EshopCommunity\Internal\Domain\Media\MediaUploader

  oxid_esales.product.media.constraint_validator.upload_validity:
    class: OxidEsales\EshopCommunity\Internal\Domain\Media\Validator\UploadValidityConstraintValidator
    tags:
      - { name: oxid.product_media.constraint_validator }

  oxid_esales.product.media.constraint_validator.size:
    class: OxidEsales\EshopCommunity\Internal\Domain\Media\Validator\FileSizeConstraintValidator
    arguments:
      $minSizeKb: '%oxid_esales.product.media.file.min_size_kb%'
      $maxSizeKb: '%oxid_esales.product.media.file.max_size_kb%'
    tags:
      - { name: oxid.product_media.constraint_validator }

  oxid_esales.product.media.constraint_validator.mime_type:
    class: OxidEsales\EshopCommunity\Internal\Domain\Media\Validator\MimeTypeConstraintValidator
    arguments:
      $baseTypePrefix: 'image/'
      $mimeTypeGuesser: "@oxid_esales.symfony.mime_types"
    tags:
      - { name: oxid.product_media.constraint_validator }

  oxid_esales.product.media.constraint_validator.file_extension:
    class: OxidEsales\EshopCommunity\Internal\Domain\Media\Validator\FileExtensionConstraintValidator
    arguments:
      $mimeTypeGuesser: "@oxid_esales.symfony.mime_types"
    tags:
      - { name: oxid.product_media.constraint_validator }

  OxidEsales\EshopCommunity\Internal\Domain\Product\Media\Validator\ProductMediaValidator:
    arguments:
      $validators: !tagged_iterator oxid.product_media.constraint_validator
