imports:
  - { resource: TemplateLogic/services.yaml }
  - { resource: Translator/services.yaml }

services:
  _defaults:
    autowire: true
    public: false

  OxidEsales\EshopCommunity\Internal\Transition\Adapter\ShopAdapterInterface:
    class: OxidEsales\EshopCommunity\Internal\Transition\Adapter\ShopAdapter

  OxidEsales\EshopCommunity\Internal\Framework\Config\Dao\ShopConfigurationSettingDaoInterface:
    class: OxidEsales\EshopCommunity\Internal\Framework\Config\Dao\ShopConfigurationSettingDao
    public: true

  OxidEsales\EshopCommunity\Internal\Framework\Theme\Config\Dao\ThemeSettingDaoInterface:
    class: OxidEsales\EshopCommunity\Internal\Framework\Theme\Config\Dao\ThemeSettingDao

  OxidEsales\EshopCommunity\Internal\Framework\Config\Utility\ShopSettingEncoderInterface:
    class: OxidEsales\EshopCommunity\Internal\Framework\Config\Utility\ShopSettingEncoder

  OxidEsales\EshopCommunity\Internal\Transition\Adapter\Email\EmailAdapterInterface:
    class: OxidEsales\EshopCommunity\Internal\Transition\Adapter\Email\SymfonyMailerAdapter
    public: true

  OxidEsales\EshopCommunity\Internal\Transition\Adapter\Http\ShopExceptionResponseListener:
    arguments:
      $debugMode: '%oxid_esales.debug_mode%'
    tags:
      - { name: kernel.event_subscriber }

  OxidEsales\EshopCommunity\Internal\Transition\Adapter\Http\SessionCommitListener:
    tags:
      - { name: kernel.event_subscriber }
