services:
  _defaults:
    autowire: true
    public: false

  oxid_esales.command.theme_clearcache_command:
    class: OxidEsales\EshopCommunity\Internal\Framework\Theme\Command\ClearCacheCommand
    tags:
      - { name: 'console.command', command: 'oe:cache:clear' }
