codeception:
  title: codeception_acceptance
  suite: 'acceptance,acceptanceAdmin'
  logfile:
    prefix: 'codeception'
  output:
    prefix: 'codeception-artifacts'
  coverage:
    path: ''
    prefix: coverage-reports-codeception_acceptance
