codeception:
  title: codeception_shop_setup
  load_shop: '{{ .Data.prepare_shop.cache.prefix }}'
  container:
    # yamllint disable-line rule:line-length
    options: '-e SELENIUM_SERVER_HOST=selenium -e BROWSER_NAME=chrome -e DB_NAME=setup_test -e DB_USERNAME=root -e DB_PASSWORD=root -e DB_HOST=mysql -e DB_PORT=3306 -e SHOP_URL=http://localhost.local/ -e SHOP_SOURCE_PATH=/var/www/source/'
  suite: 'AcceptanceSetup'
  additional_options: ''
  logfile:
    prefix: 'shop_setup'
  output:
    prefix: 'shop_setup-artifacts'
  coverage:
    path: ''
