phpunit:
  title: 'integration_tests'
  container:
    options: '-e XDEBUG_MODE=coverage'
  test: 'tests/Integration'
  additional_options: '--bootstrap tests/bootstrap.php --coverage-clover=/var/www/coverage_phpunit_integration.xml'
  logfile:
    prefix: 'phpunit_integration'
  output:
    prefix: 'integration_artifacts'
    files: |
      source/integration_coverage.xml
      generated_testplan.yaml
      source/source/log/oxideshop.log
      data/php/logs/error_log.txt
  coverage:
    path: 'source/coverage_phpunit_integration.xml'
    prefix: coverage-reports-phpunit_integration
