# {{ $org := "oxid-esales" }}organisation: {{ $org }}
# {{ $name := "oxideshop-ce" }}name: {{ $name }}
# {{ $repo := "OXID-eSales/oxideshop_ce" }}repo: {{ $repo }}

install_shop_with_modules:
  cache:
    prepared_shop: true
  container:
    options: '-e SHOP_PATH=vendor/{{ $org}}/{{ $name }}/source'
  composer:
    transform: |
      {
          "preferred-install": {
            "oxid-esales/*": "source",
            "oxid-professional-services/*": "source",
            "ddoe/*": "source"
          },
          "require": {
              "oxid-esales/twig-component": "{{ .Data.global.composer.dev_ref }}",
              "oxid-esales/twig-admin-theme": "{{ .Data.global.composer.dev_ref }}",
              "oxid-esales/apex-theme": "{{ .Data.global.composer.dev_ref }}",
              "{{ $org }}/{{ $name }}": "{{ .Data.global.composer.ref_name }}"
          },
          "repositories": {
            "{{ $org }}/{{ $name }}": {
              "type": "git",
              "url": "https://github.com/{{ $repo }}.git"
            }
          }
      }
  output:
    files: |
      docker-compose.yml
      source/composer.json*
      source/composer.lock
      source/source/config.inc.php
      source/vendor/oxid-esales/oxideshop-ce/source/config.inc.php
      data/php/logs/error_log.txt
      files.txt

runscript: &runscript
  matrix:
    script: |
      [
        "shop:tests-unit",
        "shop:tests-integration",
        "shop:tests-codeception",
        "setup:tests-codeception-shopSetup",
        "shop:~/Unit.sh",
        "shop:~/Integration.sh",
        "shop:~/Codeception.sh",
        "setup:~/ShopSetup.sh",
        "deprecated:~/Deprecated.sh"
      ]
  shop: &shop
    path: 'vendor/{{ $org}}/{{ $name }}'
    container:
      options: '-e XDEBUG_MODE=coverage'
  setup:
    load_shop: '{{ .Data.install_shop_with_modules.cache.prepared_shop_prefix }}'
    path: 'vendor/{{ $org}}/{{ $name }}'
    custom_script_container: |
      cd vendor/oxid-esales/oxideshop-ce
      composer config -g github-oauth.github.com "${GITHUB_TOKEN}"
      composer update --no-interaction
  deprecated:
    path: 'vendor/{{ $org}}/{{ $name }}'
    composer:
      transform: |
        {
            "require-dev": {
                "oxid-esales/testing-library": "{{ .Data.global.composer.dev_ref }}",
                "oxid-esales/tests-deprecated-ce": "{{ .Data.global.composer.dev_ref }}",
                "codeception/module-webdriver": "^3.1",
                "phpunit/phpunit": "^9.1.1"
            }
        }
    custom_script: |
      # Allocate 10G swap, needed for deprected tests
      sudo fallocate -l 10G swapfile
      sudo chmod 600 swapfile
      sudo mkswap swapfile
      sudo swapon swapfile
      mkdir -p source/vendor/oxid-esales/oxideshop-ce/tests/Output
      find . >source/vendor/oxid-esales/oxideshop-ce/tests/Output/files.txt

runslim:
  <<: *runscript
  matrix:
    script: '["shop:~/PhpCsReport.sh"]'
    # script: |
    #   [
    #     "shop:phpcs-report",
    #     "shop:phpmd-report",
    #     "shop:phpstan-report",
    #     "shop:phpstan-baseline"
    #   ]

sonarcloud:
  matrix:
    testplan: '["-","~/sonarcloud_oxideshop_ce_internal.yml"]'
  strip_path: '/var/www/vendor/{{ print $org }}/{{ print $name}}/'

finish:
  slack_title: 'Shop CE ({{ .Data.global.git.shop_ref }}) by {{ .Github.Actor }}'
