install:
  add_services: 'selenium-chrome'
  git:
    sdk_ref: b-8.0.x
  script: 'source/.github/oxid-esales/install.sh'
  cache:
    prepared_shop: true
  composer:
    root_url: ''
    transform: |
      {
        "preferred-install": {
          "oxid-esales/*": "source"
        },
        "require": {
          "oxid-esales/twig-admin-theme": "dev-b-8.0.x-replace-scustomtheme-with-domain-service-OXDEV-10268",
          "oxid-esales/twig-component": "dev-b-8.0.x-replace-scustomtheme-with-domain-service-OXDEV-10268",
          "oxid-esales/oxideshop-composer-plugin": "dev-b-8.0.x-move-theme-settings-to-yaml-OXDEV-8895",
          "oxid-esales/apex-theme": "dev-b-8.0.x-move-theme-settings-to-yaml-OXDEV-8895"
        }
      }
runscript:
  matrix:
    script: |
      [
        "shop:~/unit.sh",
        "shop:~/integration.sh",
        "shop:~/codeception.sh",
      ]
  container:
    options:
      -e XDEBUG_MODE=coverage
      -e CODECEPTION_OPTIONS="--ext DotReporter --skip-group flow_theme"
      -e THEME_ID=apex
      -e SELENIUM_SERVER_HOST=selenium
      -e BROWSER_NAME=chrome
      -e GITHUB_EVENT_NAME="{{ .Github.EventName }}"
      -e GITHUB_BASE_REF="{{ .Github.BaseRef }}"
      -e GITHUB_REF="refs/heads/{{ .Data.install.git.ref }}"
      -e GITHUB_REF_NAME="{{ .Data.install.git.ref }}"

sonarcloud:
  matrix:
    testplan: '["-"]'
  strip_path: '/var/www/vendor/oxid-esales/oxideshop-ce/'
  run_cleanup: false
  target_branch: 'b-8.0.x'

finish:
  slack_title: 'Shop CE ({{ .Data.install.git.ref }}) by {{ .Github.Actor }}'
