install:
  script: 'source/.github/oxid-esales/install.sh'
  cache:
    prepared_shop: true
  composer:
    root_url: ''
    transform: |
      {
        "preferred-install": {
          "oxid-esales/*": "source",
          "oxid-professional-services/*": "source",
          "ddoe/*": "source"
        },
        "require": {
          "oxid-esales/apex-theme": "{{ .Data.install.composer.dev_ref }}",
          "oxid-esales/twig-admin-theme": "{{ .Data.install.composer.dev_ref }}",
          "oxid-esales/twig-component": "{{ .Data.install.composer.dev_ref }}"
        }
      }

runscript: &runscript
  matrix:
    script: |
      [
        "shop:~/unit.sh",
        "shop:~/integration.sh",
        "shop:~/codeception.sh acceptance 1 3",
        "shop:~/codeception.sh acceptance 2 3",
        "shop:~/codeception.sh acceptance 3 3",
        "shop:~/codeception.sh acceptanceAdmin 1 2",
        "shop:~/codeception.sh acceptanceAdmin 2 2",
        "setup:~/shop-setup.sh"
      ]
  container:
    options:
      -e XDEBUG_MODE=coverage
      -e CODECEPTION_OPTIONS="--ext DotReporter --skip-group flow_theme"
      -e THEME_ID=apex
      -e SELENIUM_SERVER_HOST=selenium
      -e BROWSER_NAME=chrome
      -e GITHUB_EVENT_NAME="{{ .Github.EventName }}"
      -e GITHUB_BASE_REF="{{ .Github.BaseRef }}"
      -e GITHUB_REF="refs/heads/{{ .Data.install.git.ref }}"
      -e GITHUB_REF_NAME="{{ .Data.install.git.ref }}"
  custom_script_container: |
    # Only needed for php 8.0 / shop 7.0.x
    sudo sed \
      -e 's|^xdebug\.remote_enable.*$|xdebug.mode = debug|' \
      -e 's|^xdebug\.remote_host.*=\(.*\)$|xdebug.client_host = \1|' \
      -i.backup /usr/local/etc/php/conf.d/xdebug.ini
  shop: &shop
    path: ''
  setup:
    <<: *shop
    load_shop: '{{ .Data.install.cache.prepared_shop_prefix }}'

runslim:
  <<: *runscript
  matrix:
    script: '["shop:~/php-cs-report.sh"]'

sonarcloud:
  matrix:
    testplan: '["-","~/sonarcloud_oxideshop_ce_internal.yaml"]'
  strip_path: '/var/www/vendor/oxid-esales/oxideshop-ce/'

finish:
  slack_title: 'Shop CE ({{ .Data.install.git.ref }}) by {{ .Github.Actor }}'
