# This config depends on the defaults.yml testplan
# Only diverging settings are defined here

codeception:
  matrix:
    testplan: '["~/codeception_acceptance_70x.yml","~/codeception_acceptanceSetup_70x.yml"]'
  # Running on public runners, this should pose no problem
  max_parallel: &codeception_max_parallel 4

phpcs_tests:
  # Check all files in the full check
  diff_only: false
  filter: '^\./source/Internal/.*\.php$'

sonarcloud:
  matrix:
    testplan: '["-","~/sonarcloud_oxideshop_ce_internal.yml"]'

finish:
  slack_title: 'Full matrix CE ({{ .Data.global.git.shop_ref }}) on {{ .Github.Repository }} by {{ .Github.Actor }}'
