install: &install
  script: 'source/.github/oxid-esales/install.sh'
  cache:
    prepared_shop: true
  composer:
    root_url: ''
    transform: |
      {
          "preferred-install": {
            "oxid-esales/*": "source",
            "oxid-professional-services/*": "source",
            "ddoe/*": "source"
          },
          "require": {
            "oxid-esales/twig-component": "{{ .Data.install.composer.dev_ref }}",
            "oxid-esales/twig-admin-theme": "{{ .Data.install.composer.dev_ref }}",
            "oxid-esales/apex-theme": "{{ .Data.install.composer.dev_ref }}",
            "twig/twig": "v3.8.0"
          }
      }
  custom_script_container: |
    echo "*************** old ********************"
    cat /usr/local/etc/php/conf.d/xdebug.ini
    sed -e 's|^xdebug\.remote_enable.*$|xdebug.mode = debug|' /usr/local/etc/php/conf.d/xdebug.ini >/tmp/xdebug.ini
    sed -e 's|^xdebug\.remote_host.*=\(.*\)$|xdebug.client_host = \1|' /tmp/xdebug.ini
    cp /tmp/xdebug.ini /usr/local/etc/php/conf.d/xdebug.ini
    echo "*************** new ********************"
    cat /usr/local/etc/php/conf.d/xdebug.ini
  output:
    files: |
      docker-compose.yml
      source/composer.json*
      source/composer.lock
      source/source/config.inc.php
      source/vendor/oxid-esales/oxideshop-ce/source/config.inc.php
      data/php/logs/error_log.txt

runscript: &runscript
  matrix:
    script: |
      [
        "shop:~/unit.sh",
        "shop:~/integration.sh",
        "shop:~/codeception.sh",
        "setup:~/shop-setup.sh"
      ]
  shop: &shop
    path: ''
    container:
      # {{ $selenium_options := "-e SELENIUM_SERVER_HOST=selenium -e BROWSER_NAME=chrome" }}
      options: '-e XDEBUG_MODE=coverage -e CODECEPTION_OPTIONS="--ext DotReporter --skip-group flow_theme" {{ $selenium_options }} -e GITHUB_EVENT_NAME="{{ .Github.EventName }}" -e GITHUB_BASE_REF="{{ .Github.BaseRef }}" -e GITHUB_REF="refs/heads/{{ .Data.install.git.ref }}" -e GITHUB_REF_NAME="{{ .Data.install.git.ref }}"'
  setup:
    <<: *shop
    load_shop: '{{ .Data.install.cache.prepared_shop_prefix }}'

runslim:
  <<: *runscript
  matrix:
    script: '["shop:~/php-cs-report.sh"]'

sonarcloud:
  matrix:
    testplan: '["-","~/sonarcloud_oxideshop_ce_internal.yaml"]'
  strip_path: '/var/www/vendor/oxid-esales/oxideshop-ce/'

finish:
  slack_title: 'Shop CE ({{ .Data.install.git.ref }}) by {{ .Github.Actor }}'
  slack_compact: true
