install:
  cache:
    prepared_shop: true
  composer:
    transform: |
      {
        "config": {
            "github-protocols": ["https"],
            "allow-plugins": {
                "oxid-esales/oxideshop-composer-plugin": true,
                "oxid-esales/oxideshop-unified-namespace-generator": true
            }
        },
        "preferred-install": {
          "oxid-esales/*": "source",
          "oxid-professional-services/*": "source",
          "ddoe/*": "source"
        },
        "require": {
            "oxid-esales/twig-component": "{{ .Data.install.composer.dev_ref }}",
            "oxid-esales/twig-admin-theme": "{{ .Data.install.composer.dev_ref }}",
            "oxid-esales/apex-theme": "{{ .Data.install.composer.dev_ref }}",
            "oxid-esales/oxideshop-ce": "{{ .Data.install.composer.ref_name }}"
        },
        "require-dev": {
            "codeception/codeception": "^5.0",
            "codeception/module-asserts": "^3.0",
            "codeception/module-db": "^3.0",
            "codeception/module-filesystem": "^3.0",
            "codeception/module-webdriver": "^3.1",
            "composer/composer": "^2.0",
            "incenteev/composer-parameter-handler": "^v2.1.4",
            "mikey179/vfsstream": "~1.6.8",
            "oxid-esales/codeception-modules": "{{ .Data.install.composer.dev_ref }}",
            "oxid-esales/codeception-page-objects": "{{ .Data.install.composer.dev_ref }}",
            "oxid-esales/developer-tools": "{{ .Data.install.composer.dev_ref }}",
            "oxid-esales/oxideshop-ide-helper": "{{ .Data.install.composer.dev_ref }}",
            "phpspec/prophecy-phpunit": "^v2.0.1",
            "phpunit/phpunit": "^9.1.1",
            "squizlabs/php_codesniffer": "^3.5.4"
        },
        "autoload-dev": {
            "psr-4": {
                "OxidEsales\\EshopCommunity\\Tests\\": "./vendor/oxid-esales/oxideshop-ce/tests"
            }
        },
        "minimum-stability": "dev",
        "bin":[
            "bin/oe-console"
        ]
      }
  output:
    files: |
      docker-compose.yml
      source/composer.json*
      source/composer.lock
      source/source/config.inc.php
      source/vendor/oxid-esales/oxideshop-ce/source/config.inc.php
      data/php/logs/error_log.txt

runscript: &runscript
  matrix:
    script: |
      [
        "shop:~/unit.sh",
        "shop:~/integration.sh",
        "shop:~/codeception.sh",
        "setup:~/shop-setup.sh"
      ]
  container:
    # {{ $default_options := "-e XDEBUG_MODE=coverage -e THEME_ID=apex" }}
    # {{ $selenium_options := "-e SELENIUM_SERVER_HOST=selenium -e BROWSER_NAME=chrome" }}
    options: '-e CODECEPTION_OPTIONS="--ext DotReporter --skip-group flow_theme" {{ $default_options}} {{ $selenium_options }} -e GITHUB_EVENT_NAME="{{ .Github.EventName }}" -e GITHUB_BASE_REF="{{ .Github.BaseRef }}" -e GITHUB_REF="refs/heads/{{ .Data.install.git.ref }}" -e GITHUB_REF_NAME="{{ .Data.install.git.ref }}"'
  custom_script_container: |
    # Only needed for php 8.0 / shop 7.0.x
    sudo sed \
      -e 's|^xdebug\.remote_enable.*$|xdebug.mode = debug|' \
      -e 's|^xdebug\.remote_host.*=\(.*\)$|xdebug.client_host = \1|' \
      -i.backup /usr/local/etc/php/conf.d/xdebug.ini
  shop: &shop
    path: 'vendor/oxid-esales/oxideshop-ce'
    workdir: 'vendor/oxid-esales/oxideshop-ce'
  setup:
    <<: *shop
    load_shop: '{{ .Data.install.cache.prepared_shop_prefix }}'

runslim:
  <<: *runscript
  matrix:
    script: '["shop:~/php-cs-report.sh"]'

sonarcloud:
  matrix:
    testplan: '["-","~/sonarcloud_oxideshop_ce_internal.yaml"]'
  strip_path: '/var/www/vendor/oxid-esales/oxideshop-ce/'

finish:
  slack_title: 'Shop CE ({{ .Data.install.git.shop_ref }}) by {{ .Github.Actor }}'
  slack_compact: true
