install:
  script: 'source/.github/oxid-esales/install.sh'
  cache:
    prepared_shop: true
  composer:
    root_url: ''
    transform: |
      {
        "preferred-install": {
          "oxid-esales/*": "source"
        },
        "require": {
          "oxid-esales/apex-theme": "dev-b-7.6.x-update-vite-OXDEV-10553"
        }
      }

runscript:
  matrix:
    script: |
      [
        "shop:~/unit.sh",
        "shop:~/integration.sh",
        "shop:~/codeception.sh",
      ]
  container:
    options:
      -e XDEBUG_MODE=coverage
      -e CODECEPTION_OPTIONS="--ext DotReporter --skip-group flow_theme"
      -e THEME_ID=apex
      -e SELENIUM_SERVER_HOST=selenium
      -e BROWSER_NAME=chrome
      -e GITHUB_EVENT_NAME="{{ .Github.EventName }}"
      -e GITHUB_BASE_REF="{{ .Github.BaseRef }}"
      -e GITHUB_REF="refs/heads/{{ .Data.install.git.ref }}"
      -e GITHUB_REF_NAME="{{ .Data.install.git.ref }}"

sonarcloud:
  matrix:
    testplan: '["-"]'
  strip_path: '/var/www/vendor/oxid-esales/oxideshop-ce/'
  run_cleanup: false
  target_branch: 'b-7.6.x'

finish:
  slack_title: 'Shop CE ({{ .Data.install.git.ref }}) by {{ .Github.Actor }}'
