# This config depends on the defaults.yml testplan
# Only diverging settings are defined here
phpunit:
  additional_options: ''
  coverage:
    path: ''

codeception:
  # Running on public runners, this should pose no problem
  max_parallel: &codeception_max_parallel 4
  coverage:
    path: ''

runtest:
  matrix:
    testplan: 'skip'

sonarcloud:
  matrix:
    testplan: 'skip'

phpcs_tests:
  skip: true

finish:
  slack_title: 'Slim matrix CE ({{ .Data.global.git.shop_ref }}) on {{ .Github.Repository }} by {{ .Github.Actor }}'
