# This config depends on the defaults.yaml testplan
# Only diverging settings are defined here

prepare_shop:
  composer:
    transform: |
      {
          "require": {
              "oxid-esales/smarty-component": "dev-b-7.0.x",
              "oxid-esales/smarty-admin-theme": "dev-b-7.0.x",
              "oxid-esales/flow-theme": "dev-b-7.0.x"
          },
          "require-dev": {
              "oxid-esales/codeception-page-objects": "dev-b-7.0.x",
              "oxid-esales/codeception-modules": "dev-b-7.0.x"
          }
      }

skip: &skip
  matrix:
    testplan: 'skip'
  skip: true

phpunit: *skip
codeception: *skip
sonarcloud: *skip
phpcs_tests: *skip
yamllint: *skip
actionlint: *skip

runtest:
  matrix:
    testplan: '["-"]'
  container:
    method: exec
    options: '-e XDEBUG_MODE=coverage -e THEME_ID=flow -e ACTIVE_THEME=flow'

finish:
  slack_title: 'Shop CE 7.0.x with Smarty on {{ .Github.Repository }} by {{ .Github.Actor }}'
