# This config depends on the defaults.yml testplan
# Only diverging settings are defined here

prepare_shop:
  git: *git
  composer:
    transform: |
      {
          "require": {
              "oxid-esales/smarty-component": "dev-b-7.0.x",
              "oxid-esales/smarty-admin-theme": "dev-b-7.0.x",
              "oxid-esales/flow-theme": "dev-b-7.0.x"
          },
          "require-dev": {
              "oxid-esales/codeception-page-objects": "dev-b-7.0.x",
              "oxid-esales/codeception-modules": "dev-b-7.0.x"
          }
      }


phpunit:
  matrix:
    testplan: 'skip'

codeception:
  matrix:
    testplan: 'skip'

runtest:
  container:
    method: exec
    options: '-e XDEBUG_MODE=coverage -e THEME_ID=flow -e ACTIVE_THEME=flow'

sonarcloud:
  matrix:
    testplan: 'skip'

phpcs_tests:
  # Check all files in the full check
  diff_only: false
  filter: '^\./source/Internal/.*\.php$'

finish:
  slack_title: 'CE 7.0.x with Smarty on {{ .Github.Repository }} by {{ .Github.Actor }}'
