services:
  _defaults:
    autowire: true

  OxidEsales\EshopCommunity\Internal\Domain\Media\Dao\MediaDaoInterface:
    class: OxidEsales\EshopCommunity\Internal\Domain\Media\Dao\MediaDao

  OxidEsales\EshopCommunity\Internal\Domain\Media\DataMapper\DataMapperInterface:
    class: OxidEsales\EshopCommunity\Internal\Domain\Media\DataMapper\DataMapper
