parameters:
  oxid_esales.request.trusted_proxies: []

services:
  _defaults:
    autowire: true
    public: false

  OxidEsales\EshopCommunity\Internal\Framework\Request\RequestFactory:
    arguments:
      $trustedProxies: '%oxid_esales.request.trusted_proxies%'

  Symfony\Component\HttpFoundation\Request:
    factory: ['@OxidEsales\EshopCommunity\Internal\Framework\Request\RequestFactory', 'create']
    public: true

  OxidEsales\EshopCommunity\Internal\Framework\Request\RequestInterface:
    class: OxidEsales\EshopCommunity\Internal\Transition\Adapter\Request\RequestAdapter

  OxidEsales\EshopCommunity\Internal\Framework\Request\HttpsRequestResolverInterface:
    class: OxidEsales\EshopCommunity\Internal\Framework\Request\HttpsRequestResolver
    public: true
