parameters:
  oxid_esales.request.trusted_proxies: []

services:
  _defaults:
    autowire: true
    public: false

  OxidEsales\EshopCommunity\Internal\Framework\Request\RequestFactory:
    arguments:
      $trustedProxies: '%oxid_esales.request.trusted_proxies%'

  Symfony\Component\HttpFoundation\Request:
    factory: ['@OxidEsales\EshopCommunity\Internal\Framework\Request\RequestFactory', 'create']
    public: true

  Symfony\Component\HttpFoundation\RequestStack:
    public: true

  OxidEsales\EshopCommunity\Internal\Framework\Request\RequestInterface:
    alias: Symfony\Component\HttpFoundation\Request