parameters:
  oxid_esales.log_admin_queries: false

services:
  _defaults:
    autowire: true

  OxidEsales\EshopCommunity\Internal\Framework\Database\Logger\QueryLogFilterInterface:
    class: OxidEsales\EshopCommunity\Internal\Framework\Database\Logger\QueryLogFilter
    arguments:
      $skipLogTags: '@=service("OxidEsales\\EshopCommunity\\Internal\\Transition\\Utility\\ContextInterface").getSkipLogTags()'

  OxidEsales\EshopCommunity\Internal\Framework\Database\Logger\QueryLogContextExtenderInterface:
    class: OxidEsales\EshopCommunity\Internal\Framework\Database\Logger\QueryLogContextExtender

  Psr\Log\NullLogger:
    public: true

  Doctrine\DBAL\Logging\Middleware:
    arguments:
      $logger: '@=(parameter("oxid_esales.log_admin_queries") & service("OxidEsales\\EshopCommunity\\Internal\\Transition\\Utility\\ContextInterface").isAdmin()) ? service("database.psr_logger") : service("Psr\\Log\\NullLogger")'
    tags:
      - { name: doctrine.middleware }

  database.monolog_logger_factory:
    class: OxidEsales\EshopCommunity\Internal\Framework\Database\Logger\QueryLoggerFactory
    arguments:
      $loggerName: 'OXID Admin Logger'
      $streamHandler: '@database.monolog.stream_handler'

  database.psr_logger:
    class: Monolog\Logger
    factory: ['@database.monolog_logger_factory', 'create']

  database.monolog.stream_handler:
    class: Monolog\Handler\StreamHandler
    arguments:
      $stream: '@=service("OxidEsales\\EshopCommunity\\Internal\\Transition\\Utility\\ContextInterface").getAdminLogFilePath()'
      $level: !php/const Psr\Log\LogLevel::DEBUG
    calls:
      - setFormatter: ['@Monolog\Formatter\LineFormatter']

  Monolog\Formatter\LineFormatter:
    calls:
      - includeStacktraces: []
