services:
    _defaults:
        autowire: true

    OxidEsales\EshopCommunity\Internal\Setup\Language\LanguageInstallerInterface:
        class: OxidEsales\EshopCommunity\Internal\Setup\Language\LanguageInstaller
