services:
  _defaults:
    autowire: true

  OxidEsales\EshopCommunity\Internal\Transition\Adapter\TemplateLogic\ContentFactory:

  OxidEsales\EshopCommunity\Internal\Transition\Adapter\TemplateLogic\SeoUrlLogic:

  OxidEsales\EshopCommunity\Internal\Transition\Adapter\TemplateLogic\AddUrlParametersLogic:

  OxidEsales\EshopCommunity\Internal\Transition\Adapter\TemplateLogic\IncludeDynamicLogic:

  OxidEsales\EshopCommunity\Internal\Transition\Adapter\TemplateLogic\IfContentLogic:

  OxidEsales\EshopCommunity\Internal\Transition\Adapter\TemplateLogic\FormatPriceLogic:

  OxidEsales\EshopCommunity\Internal\Transition\Adapter\TemplateLogic\ScriptLogic:

  OxidEsales\EshopCommunity\Internal\Transition\Adapter\TemplateLogic\FormatDateLogic:

  OxidEsales\EshopCommunity\Internal\Transition\Adapter\TemplateLogic\TranslateFilterLogic:

  OxidEsales\EshopCommunity\Internal\Transition\Adapter\TemplateLogic\TranslateFunctionLogic:

  OxidEsales\EshopCommunity\Internal\Transition\Adapter\TemplateLogic\FormatTimeLogic:

  OxidEsales\EshopCommunity\Internal\Transition\Adapter\TemplateLogic\FileSizeLogic:

  OxidEsales\EshopCommunity\Internal\Transition\Adapter\TemplateLogic\StyleLogic:

  OxidEsales\EshopCommunity\Internal\Transition\Adapter\TemplateLogic\TruncateLogic:

  OxidEsales\EshopCommunity\Internal\Transition\Adapter\TemplateLogic\TranslateSalutationLogic:

  OxidEsales\EshopCommunity\Internal\Transition\Adapter\TemplateLogic\FormatCurrencyLogic:

  OxidEsales\EshopCommunity\Internal\Transition\Adapter\TemplateLogic\WordwrapLogic:

  OxidEsales\EshopCommunity\Internal\Transition\Adapter\TemplateLogic\IncludeWidgetLogic:

  OxidEsales\EshopCommunity\Internal\Transition\Adapter\TemplateLogic\SmartWordwrapLogic:

  OxidEsales\EshopCommunity\Internal\Transition\Adapter\TemplateLogic\InputHelpLogic:

  OxidEsales\EshopCommunity\Internal\Transition\Adapter\TemplateLogic\DateFormatHelper:
    deprecated:
      package: 'oxid-esales/oxideshop-ce'
      version: '7.3.0'
      message: 'The "%service_id%" service is deprecated.'

  OxidEsales\EshopCommunity\Internal\Transition\Adapter\TemplateLogic\InsertNewBasketItemLogicTwig:
