imports:
    - { resource: ./parameter.yaml }
    - { resource: Admin/services.yaml }
    - { resource: Authentication/services.yaml }
    - { resource: Contact/services.yaml }
    - { resource: Media/services.yaml }
    - { resource: Newsletter/services.yaml }
    - { resource: Product/Media/parameters.yaml }
    - { resource: Product/Media/services.yaml }
    - { resource: Product/Search/services.yaml }
    - { resource: Review/services.yaml }
