#
# Add missing indices
#

ALTER TABLE `oxarticles2shop` ADD UNIQUE KEY `OXMAPIDX` (`OXSHOPID`,`OXMAPOBJECTID`);
ALTER TABLE `oxarticles2shop` ADD KEY `OXMAPOBJECTID` (`OXMAPOBJECTID`);
ALTER TABLE `oxarticles2shop` ADD KEY `OXSHOPID` (`OXSHOPID`);

ALTER TABLE `oxcategories2shop` ADD UNIQUE KEY `OXMAPIDX` (`OXSHOPID`,`OXMAPOBJECTID`);
ALTER TABLE `oxcategories2shop` ADD KEY `OXMAPOBJECTID` (`OXMAPOBJECTID`);
ALTER TABLE `oxcategories2shop` ADD KEY `OXSHOPID` (`OXSHOPID`);

ALTER TABLE `oxobject2category2shop` ADD UNIQUE KEY `OXMAPIDX` (`OXSHOPID`,`OXMAPOBJECTID`);
ALTER TABLE `oxobject2category2shop` ADD KEY `OXMAPOBJECTID` (`OXMAPOBJECTID`);
ALTER TABLE `oxobject2category2shop` ADD KEY `OXSHOPID` (`OXSHOPID`);

ALTER TABLE `oxmanufacturers2shop` ADD UNIQUE KEY `OXMAPIDX` (`OXSHOPID`,`OXMAPOBJECTID`);
ALTER TABLE `oxmanufacturers2shop` ADD KEY `OXMAPOBJECTID` (`OXMAPOBJECTID`);
ALTER TABLE `oxmanufacturers2shop` ADD KEY `OXSHOPID` (`OXSHOPID`);

ALTER TABLE `oxvendor2shop` ADD UNIQUE KEY `OXMAPIDX` (`OXSHOPID`,`OXMAPOBJECTID`);
ALTER TABLE `oxvendor2shop` ADD KEY `OXMAPOBJECTID` (`OXMAPOBJECTID`);
ALTER TABLE `oxvendor2shop` ADD KEY `OXSHOPID` (`OXSHOPID`);
