#
# Add missing indices
#

ALTER TABLE `oxarticles2shop` ADD UNIQUE KEY `OXMAPIDX` (`OXMAPSHOPID`,`OXMAPOBJECTID`);
ALTER TABLE `oxarticles2shop` ADD KEY `OXMAPOBJECTID` (`OXMAPOBJECTID`);
ALTER TABLE `oxarticles2shop` ADD KEY `OXMAPSHOPID`   (`OXMAPSHOPID`);

ALTER TABLE `oxcategories2shop` ADD UNIQUE KEY `OXMAPIDX` (`OXMAPSHOPID`,`OXMAPOBJECTID`);
ALTER TABLE `oxcategories2shop` ADD KEY `OXMAPOBJECTID` (`OXMAPOBJECTID`);
ALTER TABLE `oxcategories2shop` ADD KEY `OXMAPSHOPID`   (`OXMAPSHOPID`);

ALTER TABLE `oxobject2category2shop` ADD UNIQUE KEY `OXMAPIDX` (`OXMAPSHOPID`,`OXMAPOBJECTID`);
ALTER TABLE `oxobject2category2shop` ADD KEY `OXMAPOBJECTID` (`OXMAPOBJECTID`);
ALTER TABLE `oxobject2category2shop` ADD KEY `OXMAPSHOPID`   (`OXMAPSHOPID`);

ALTER TABLE `oxmanufacturers2shop` ADD UNIQUE KEY `OXMAPIDX` (`OXMAPSHOPID`,`OXMAPOBJECTID`);
ALTER TABLE `oxmanufacturers2shop` ADD KEY `OXMAPOBJECTID` (`OXMAPOBJECTID`);
ALTER TABLE `oxmanufacturers2shop` ADD KEY `OXMAPSHOPID`   (`OXMAPSHOPID`);

ALTER TABLE `oxvendor2shop` ADD UNIQUE KEY `OXMAPIDX` (`OXMAPSHOPID`,`OXMAPOBJECTID`);
ALTER TABLE `oxvendor2shop` ADD KEY `OXMAPOBJECTID` (`OXMAPOBJECTID`);
ALTER TABLE `oxvendor2shop` ADD KEY `OXMAPSHOPID`   (`OXMAPSHOPID`);
