#
# Drop OXSHOPINCL and OXSHOPEXCL columns from multi-shop tables.
#

ALTER TABLE `oxarticles` DROP COLUMN `OXSHOPINCL`, DROP COLUMN `OXSHOPEXCL`;
ALTER TABLE `oxattribute` DROP COLUMN `OXSHOPINCL`, DROP COLUMN `OXSHOPEXCL`;
ALTER TABLE `oxcategories` DROP COLUMN `OXSHOPINCL`, DROP COLUMN `OXSHOPEXCL`;
ALTER TABLE `oxdelivery` DROP COLUMN `OXSHOPINCL`, DROP COLUMN `OXSHOPEXCL`;
ALTER TABLE `oxdeliveryset` DROP COLUMN `OXSHOPINCL`, DROP COLUMN `OXSHOPEXCL`;
ALTER TABLE `oxdiscount` DROP COLUMN `OXSHOPINCL`, DROP COLUMN `OXSHOPEXCL`;
ALTER TABLE `oxlinks` DROP COLUMN `OXSHOPINCL`, DROP COLUMN `OXSHOPEXCL`;
ALTER TABLE `oxmanufacturers` DROP COLUMN `OXSHOPINCL`, DROP COLUMN `OXSHOPEXCL`;
ALTER TABLE `oxnews` DROP COLUMN `OXSHOPINCL`, DROP COLUMN `OXSHOPEXCL`;
ALTER TABLE `oxobject2category` DROP COLUMN `OXSHOPINCL`, DROP COLUMN `OXSHOPEXCL`;
ALTER TABLE `oxvoucherseries` DROP COLUMN `OXSHOPINCL`, DROP COLUMN `OXSHOPEXCL`;
ALTER TABLE `oxselectlist` DROP COLUMN `OXSHOPINCL`, DROP COLUMN `OXSHOPEXCL`;
ALTER TABLE `oxwrapping` DROP COLUMN `OXSHOPINCL`, DROP COLUMN `OXSHOPEXCL`;
ALTER TABLE `oxvendor` DROP COLUMN `OXSHOPINCL`, DROP COLUMN `OXSHOPEXCL`;
