services:
    _defaults:
        autowire: true

    OxidEsales\EshopCommunity\Internal\Domain\Admin\Command\CreateUserCommand:
        class: OxidEsales\EshopCommunity\Internal\Domain\Admin\Command\CreateUserCommand
        tags:
            - { name: 'console.command', command: 'oe:admin:create-user' }
