services:
  _defaults:
    autowire: true

  OxidEsales\EshopCommunity\Internal\Framework\Theme\Path\Service\ThemePathResolverInterface:
    class: OxidEsales\EshopCommunity\Internal\Framework\Theme\Path\Service\ThemePathResolver
    public: true
