services:
  _defaults:
    autowire: true

  OxidEsales\EshopCommunity\Internal\Framework\Migration\MigrationExecutorInterface:
    class: OxidEsales\EshopCommunity\Internal\Framework\Migration\MigrationExecutor
