imports:
  - { resource: Command/services.yaml }

services:
  _defaults:
    autowire: true
    public: false

  OxidEsales\EshopCommunity\Internal\Framework\Migration\MigrationExecutor: ~

  OxidEsales\EshopCommunity\Internal\Framework\Migration\TaggedMigrationExecutor:
    public: true
    arguments:
      $providers: !tagged_iterator oxid_esales.migration_path_provider

  OxidEsales\EshopCommunity\Internal\Framework\Migration\MigrationOptionsForwarderInterface:
    class: OxidEsales\EshopCommunity\Internal\Framework\Migration\MigrationOptionsForwarder

  OxidEsales\EshopCommunity\Internal\Framework\Migration\MigrationExitCodeResolverInterface:
    class: OxidEsales\EshopCommunity\Internal\Framework\Migration\MigrationExitCodeResolver
