services:
  _defaults:
    autowire: true
    public: false

  OxidEsales\EshopCommunity\Internal\Framework\Migration\Command\DatabaseMigrateCommand:
    tags:
      - { name: 'console.command', command: 'oe:database:migrate' }
