services:
    _defaults:
        autowire: true

    OxidEsales\EshopCommunity\Internal\Setup\Htaccess\HtaccessDaoFactoryInterface:
        class: OxidEsales\EshopCommunity\Internal\Setup\Htaccess\HtaccessDaoFactory

    OxidEsales\EshopCommunity\Internal\Setup\Htaccess\HtaccessUpdaterInterface:
        class: OxidEsales\EshopCommunity\Internal\Setup\Htaccess\HtaccessUpdater
