services:
  _defaults:
    autowire: true

  Symfony\Component\EventDispatcher\EventDispatcherInterface:
    class: Symfony\Component\EventDispatcher\EventDispatcher
    public: true

  Symfony\Contracts\EventDispatcher\EventDispatcherInterface:
    alias: Symfony\Component\EventDispatcher\EventDispatcherInterface

  event_dispatcher:
    alias: Symfony\Component\EventDispatcher\EventDispatcherInterface
