parameters:
  oxid_esales.theme.admin.name: 'admin_twig'

services:
  _defaults:
    autowire: true

  OxidEsales\EshopCommunity\Internal\Framework\Theme\Bridge\AdminThemeBridgeInterface:
    class: OxidEsales\EshopCommunity\Internal\Framework\Theme\Bridge\AdminThemeBridge
    arguments:
      - '%oxid_esales.theme.admin.name%'
    public: true

  OxidEsales\EshopCommunity\Internal\Framework\Theme\Command\ThemeActivateCommand:
    tags:
      - { name: 'console.command', command: 'oe:theme:activate' }
