imports:
  - { resource: MetaData/services.yaml }
  - { resource: Inheritance/services.yaml }
  - { resource: Setup/services.yaml }
  - { resource: State/services.yaml }
  - { resource: Cache/services.yaml }
  - { resource: Configuration/services.yaml }
  - { resource: Path/services.yaml }
  - { resource: ParentInfo/services.yaml }

parameters:
  oxid_esales.theme.admin.name: 'admin_twig'
  oxid_esales.theme.admin.media.image_grid_size: '400*400'
  oxid_esales.theme.admin.media.image_zoom_size: '800*800'
  oxid_esales.theme.media.allowed_image_sizes:
    - '%oxid_esales.theme.admin.media.image_grid_size%'
    - '%oxid_esales.theme.admin.media.image_zoom_size%'

services:
  _defaults:
    autowire: true

  OxidEsales\EshopCommunity\Internal\Framework\Theme\Bridge\AdminThemeBridgeInterface:
    class: OxidEsales\EshopCommunity\Internal\Framework\Theme\Bridge\AdminThemeBridge
    arguments:
      - '%oxid_esales.theme.admin.name%'
    public: true

  OxidEsales\EshopCommunity\Internal\Framework\Theme\Facade\ThemeSettingServiceInterface:
    class: OxidEsales\EshopCommunity\Internal\Framework\Theme\Facade\ThemeSettingService
    public: true

  OxidEsales\EshopCommunity\Internal\Framework\Theme\Command\ThemeActivateCommand:
    tags:
      - { name: 'console.command', command: 'oe:theme:activate' }

  OxidEsales\EshopCommunity\Application\Controller\Admin\ThemeMain:
    tags:
      - { name: 'oxid.view_controller', controller_key: 'theme_main' }
    public: true
