parameters:
  oxid_esales.theme.admin.name: 'admin'

services:
  _defaults:
    autowire: true
    public: false

  OxidEsales\EshopCommunity\Internal\Theme\Bridge\AdminThemeBridgeInterface:
    class: OxidEsales\EshopCommunity\Internal\Theme\Bridge\AdminThemeBridge
    arguments:
      - '%oxid_esales.theme.admin.name%'
    public: true
