<?php

/**
 * Copyright © OXID eSales AG. All rights reserved.
 * See LICENSE file for license details.
 */

namespace OxidEsales\EshopCommunity\Core\Routing;

use OxidEsales\Eshop\Application\Component\Widget as Widget;
use OxidEsales\Eshop\Application\Controller as Controller;
use OxidEsales\Eshop\Core\Contract\ControllerMapProviderInterface;

/**
 * This class determines the controllers which should be allowed to be called directly via
 * HTTP GET/POST Parameters, inside form actions or with oxid_include_widget.
 * Those controllers are specified e.g. inside a form action with a controller key which is mapped to its class.
 *
 * @internal Do not make a module extension for this class.
 * @see      https://oxidforge.org/en/core-oxid-eshop-classes-must-not-be-extended.html
 */
class ShopControllerMapProvider implements ControllerMapProviderInterface
{
    private $controllerMap = [
        'language' => Controller\Admin\LanguageController::class,
        'module' => Controller\Admin\ModuleController::class,
        'theme' => Controller\Admin\ThemeController::class,
        'manufacturerlist' => Controller\ManufacturerListController::class,
        'review' => Controller\ReviewController::class,
        'vendorlist' => Controller\VendorListController::class,
        'actions' => Controller\Admin\ActionsController::class,
        'account_user' => Controller\AccountUserController::class,
        'account_wishlist' => Controller\AccountWishlistController::class,
        'vendor_main' => Controller\Admin\VendorMain::class,
        'vendor_main_ajax' => Controller\Admin\VendorMainAjax::class,
        'vendor_seo' => Controller\Admin\VendorSeo::class,
        'voucherserie' => Controller\Admin\VoucherSerieController::class,
        'voucherserie_export' => Controller\Admin\VoucherSerieExport::class,
        'voucherserie_generate' => Controller\Admin\VoucherSerieGenerate::class,
        'voucherserie_groups' => Controller\Admin\VoucherSerieGroups::class,
        'voucherserie_groups_ajax' => Controller\Admin\VoucherSerieGroupsAjax::class,
        'voucherserie_list' => Controller\Admin\VoucherSerieList::class,
        'voucherserie_main' => Controller\Admin\VoucherSerieMain::class,
        'wrapping_list' => Controller\Admin\WrappingList::class,
        'wrapping_main' => Controller\Admin\WrappingMain::class,
        'genexport' => Controller\Admin\GenericExport::class,
        'genexport_do' => Controller\Admin\GenericExportDo::class,
        'genexport_main' => Controller\Admin\GenericExportMain::class,
        'genimport' => Controller\Admin\GenericImport::class,
        'language_list' => Controller\Admin\LanguageList::class,
        'language_main' => Controller\Admin\LanguageMain::class,
        'list_review' => Controller\Admin\ListReview::class,
        'list_user' => Controller\Admin\ListUser::class,
        'login' => Controller\Admin\LoginController::class,
        'manufacturer' => Controller\Admin\ManufacturerController::class,
        'manufacturer_list' => Controller\Admin\ManufacturerList::class,
        'manufacturer_main' => Controller\Admin\ManufacturerMain::class,
        'manufacturer_main_ajax' => Controller\Admin\ManufacturerMainAjax::class,
        'manufacturer_seo' => Controller\Admin\ManufacturerSeo::class,
        'module_config' => Controller\Admin\ModuleConfiguration::class,
        'module_list' => Controller\Admin\ModuleList::class,
        'module_main' => Controller\Admin\ModuleMain::class,
        'module_sortlist' => Controller\Admin\ModuleSortList::class,
        'navigation' => Controller\Admin\NavigationController::class,
        'newsletter_list' => Controller\Admin\NewsletterList::class,
        'newsletter_main' => Controller\Admin\NewsletterMain::class,
        'newsletter_plain' => Controller\Admin\NewsletterPlain::class,
        'newsletter_preview' => Controller\Admin\NewsletterPreview::class,
        'newsletter_selection' => Controller\Admin\NewsletterSelection::class,
        'newsletter_selection_ajax' => Controller\Admin\NewsletterSelectionAjax::class,
        'newsletter_send' => Controller\Admin\NewsletterSend::class,
        'order_address' => Controller\Admin\OrderAddress::class,
        'order_article' => Controller\Admin\OrderArticle::class,
        'order_downloads' => Controller\Admin\OrderDownloads::class,
        'order_main' => Controller\Admin\OrderMain::class,
        'order_overview' => Controller\Admin\OrderOverview::class,
        'order_remark' => Controller\Admin\OrderRemark::class,
        'oxnavigationtree' => Controller\Admin\NavigationTree::class,
        'payment_country' => Controller\Admin\PaymentCountry::class,
        'payment_country_ajax' => Controller\Admin\PaymentCountryAjax::class,
        'payment_list' => Controller\Admin\PaymentList::class,
        'payment_main' => Controller\Admin\PaymentMain::class,
        'payment_main_ajax' => Controller\Admin\PaymentMainAjax::class,
        'payment_rdfa' => Controller\Admin\PaymentRdfa::class,
        'pricealarm_list' => Controller\Admin\PriceAlarmList::class,
        'pricealarm_mail' => Controller\Admin\PriceAlarmMail::class,
        'pricealarm_main' => Controller\Admin\PriceAlarmMain::class,
        'pricealarm_send' => Controller\Admin\PriceAlarmSend::class,
        'selectlist' => Controller\Admin\SelectListController::class,
        'selectlist_list' => Controller\Admin\SelectListList::class,
        'selectlist_main' => Controller\Admin\SelectListMain::class,
        'selectlist_main_ajax' => Controller\Admin\SelectListMainAjax::class,
        'selectlist_order_ajax' => Controller\Admin\SelectListOrderAjax::class,
        'shop' => Controller\Admin\ShopController::class,
        'shop_default_category_ajax' => Controller\Admin\ShopDefaultCategoryAjax::class,
        'shop_license' => Controller\Admin\ShopLicense::class,
        'shop_list' => Controller\Admin\ShopList::class,
        'shop_main' => Controller\Admin\ShopMain::class,
        'shop_performance' => Controller\Admin\ShopPerformance::class,
        'shop_rdfa' => Controller\Admin\ShopRdfa::class,
        'shop_seo' => Controller\Admin\ShopSeo::class,
        'shop_system' => Controller\Admin\ShopSystem::class,
        'sysreq' => Controller\Admin\SystemRequirements::class,
        'sysreq_list' => Controller\Admin\SystemRequirementsList::class,
        'sysreq_main' => Controller\Admin\SystemRequirementsMain::class,
        'systeminfo' => Controller\Admin\SystemInfoController::class,
        'theme_config' => Controller\Admin\ThemeConfiguration::class,
        'theme_list' => Controller\Admin\ThemeList::class,
        'theme_main' => Controller\Admin\ThemeMain::class,
        'tools' => Controller\Admin\ToolsController::class,
        'tools_list' => Controller\Admin\ToolsList::class,
        'tools_main' => Controller\Admin\ToolsMain::class,
        'user_address' => Controller\Admin\UserAddress::class,
        'user_article' => Controller\Admin\UserArticle::class,
        'user_extend' => Controller\Admin\UserExtend::class,
        'user_main' => Controller\Admin\UserMain::class,
        'user_main_ajax' => Controller\Admin\UserMainAjax::class,
        'user_overview' => Controller\Admin\UserOverview::class,
        'user_payment' => Controller\Admin\UserPayment::class,
        'user_remark' => Controller\Admin\UserRemark::class,
        'usergroup' => Controller\Admin\UserGroupController::class,
        'usergroup_list' => Controller\Admin\UserGroupList::class,
        'usergroup_main' => Controller\Admin\UserGroupMain::class,
        'usergroup_main_ajax' => Controller\Admin\UserGroupMainAjax::class,
        'vendor' => Controller\Admin\VendorController::class,
        'vendor_list' => Controller\Admin\VendorList::class,
        'actions_article_ajax' => Controller\Admin\ActionsArticleAjax::class,
        'actions_groups_ajax' => Controller\Admin\ActionsGroupsAjax::class,
        'actions_list' => Controller\Admin\ActionsList::class,
        'actions_main' => Controller\Admin\ActionsMain::class,
        'actions_main_ajax' => Controller\Admin\ActionsMainAjax::class,
        'actions_order_ajax' => Controller\Admin\ActionsOrderAjax::class,
        'admin_content' => Controller\Admin\AdminContent::class,
        'admin_links' => Controller\Admin\AdminLinks::class,
        'admin_newsletter' => Controller\Admin\AdminNewsletter::class,
        'admin_order' => Controller\Admin\AdminOrder::class,
        'admin_payment' => Controller\Admin\AdminPayment::class,
        'admin_pricealarm' => Controller\Admin\AdminPriceAlarm::class,
        'admin_start' => Controller\Admin\AdminStart::class,
        'admin_user' => Controller\Admin\AdminUser::class,
        'admin_wrapping' => Controller\Admin\AdminWrapping::class,
        'adminlinks_list' => Controller\Admin\AdminlinksList::class,
        'adminlinks_main' => Controller\Admin\AdminlinksMain::class,
        'article' => Controller\Admin\ArticleController::class,
        'article_accessories_ajax' => Controller\Admin\ArticleAccessoriesAjax::class,
        'article_attribute' => Controller\Admin\ArticleAttribute::class,
        'article_attribute_ajax' => Controller\Admin\ArticleAttributeAjax::class,
        'article_bundle_ajax' => Controller\Admin\ArticleBundleAjax::class,
        'article_crossselling' => Controller\Admin\ArticleCrossselling::class,
        'article_crossselling_ajax' => Controller\Admin\ArticleCrosssellingAjax::class,
        'article_extend' => Controller\Admin\ArticleExtend::class,
        'article_extend_ajax' => Controller\Admin\ArticleExtendAjax::class,
        'article_files' => Controller\Admin\ArticleFiles::class,
        'article_main' => Controller\Admin\ArticleMain::class,
        'article_overview' => Controller\Admin\ArticleOverview::class,
        'article_pictures' => Controller\Admin\ArticlePictures::class,
        'article_review' => Controller\Admin\ArticleReview::class,
        'article_selection_ajax' => Controller\Admin\ArticleSelectionAjax::class,
        'article_seo' => Controller\Admin\ArticleSeo::class,
        'article_stock' => Controller\Admin\ArticleStock::class,
        'article_userdef' => Controller\Admin\ArticleUserdef::class,
        'article_variant' => Controller\Admin\ArticleVariant::class,
        'attribute' => Controller\Admin\AttributeController::class,
        'attribute_category' => Controller\Admin\AttributeCategory::class,
        'attribute_category_ajax' => Controller\Admin\AttributeCategoryAjax::class,
        'attribute_list' => Controller\Admin\AttributeList::class,
        'attribute_main' => Controller\Admin\AttributeMain::class,
        'attribute_main_ajax' => Controller\Admin\AttributeMainAjax::class,
        'attribute_order_ajax' => Controller\Admin\AttributeOrderAjax::class,
        'category' => Controller\Admin\CategoryController::class,
        'category_list' => Controller\Admin\CategoryList::class,
        'category_main' => Controller\Admin\CategoryMain::class,
        'category_main_ajax' => Controller\Admin\CategoryMainAjax::class,
        'category_order' => Controller\Admin\CategoryOrder::class,
        'category_order_ajax' => Controller\Admin\CategoryOrderAjax::class,
        'category_pictures' => Controller\Admin\CategoryPictures::class,
        'category_seo' => Controller\Admin\CategorySeo::class,
        'category_text' => Controller\Admin\CategoryText::class,
        'category_update' => Controller\Admin\CategoryUpdate::class,
        'content_list' => Controller\Admin\ContentList::class,
        'content_main' => Controller\Admin\ContentMain::class,
        'content_seo' => Controller\Admin\ContentSeo::class,
        'country' => Controller\Admin\CountryController::class,
        'country_list' => Controller\Admin\CountryList::class,
        'country_main' => Controller\Admin\CountryMain::class,
        'delivery' => Controller\Admin\DeliveryController::class,
        'delivery_articles' => Controller\Admin\DeliveryArticles::class,
        'delivery_articles_ajax' => Controller\Admin\DeliveryArticlesAjax::class,
        'delivery_categories_ajax' => Controller\Admin\DeliveryCategoriesAjax::class,
        'delivery_groups_ajax' => Controller\Admin\DeliveryGroupsAjax::class,
        'delivery_list' => Controller\Admin\DeliveryList::class,
        'delivery_main' => Controller\Admin\DeliveryMain::class,
        'delivery_main_ajax' => Controller\Admin\DeliveryMainAjax::class,
        'delivery_users' => Controller\Admin\DeliveryUsers::class,
        'delivery_users_ajax' => Controller\Admin\DeliveryUsersAjax::class,
        'deliveryset' => Controller\Admin\DeliverySetController::class,
        'deliveryset_country_ajax' => Controller\Admin\DeliverySetCountryAjax::class,
        'deliveryset_groups_ajax' => Controller\Admin\DeliverySetGroupsAjax::class,
        'deliveryset_list' => Controller\Admin\DeliverySetList::class,
        'deliveryset_main' => Controller\Admin\DeliverySetMain::class,
        'deliveryset_main_ajax' => Controller\Admin\DeliverySetMainAjax::class,
        'deliveryset_payment' => Controller\Admin\DeliverySetPayment::class,
        'deliveryset_payment_ajax' => Controller\Admin\DeliverySetPaymentAjax::class,
        'deliveryset_rdfa' => Controller\Admin\DeliverySetRdfa::class,
        'deliveryset_users' => Controller\Admin\DeliverySetUsers::class,
        'deliveryset_users_ajax' => Controller\Admin\DeliverySetUsersAjax::class,
        'diagnostics' => Controller\Admin\DiagnosticsController::class,
        'diagnostics_list' => Controller\Admin\DiagnosticsList::class,
        'diagnostics_main' => Controller\Admin\DiagnosticsMain::class,
        'discount' => Controller\Admin\DiscountController::class,
        'discount_articles' => Controller\Admin\DiscountArticles::class,
        'discount_articles_ajax' => Controller\Admin\DiscountArticlesAjax::class,
        'discount_categories_ajax' => Controller\Admin\DiscountCategoriesAjax::class,
        'discount_groups_ajax' => Controller\Admin\DiscountGroupsAjax::class,
        'discount_item_ajax' => Controller\Admin\DiscountItemAjax::class,
        'discount_list' => Controller\Admin\DiscountList::class,
        'discount_main' => Controller\Admin\DiscountMain::class,
        'discount_main_ajax' => Controller\Admin\DiscountMainAjax::class,
        'discount_users' => Controller\Admin\DiscountUsers::class,
        'discount_users_ajax' => Controller\Admin\DiscountUsersAjax::class,
        'content' => Controller\ContentController::class,
        'links' => Controller\LinksController::class,
        'newsletter' => Controller\NewsletterController::class,
        'pricealarm' => Controller\PriceAlarmController::class,
        'account_noticelist' => Controller\AccountNoticeListController::class,
        'oxadminlist' => Controller\Admin\AdminListController::class,
        'order_list' => Controller\Admin\OrderList::class,
        'user_list' => Controller\Admin\UserList::class,
        'details' => Controller\ArticleDetailsController::class,
        'oxubase' => Controller\FrontendController::class,
        'alist' => Controller\ArticleListController::class,
        'user' => Controller\UserController::class,
        'account' => Controller\AccountController::class,
        'basket' => Controller\BasketController::class,
        'compare' => Controller\CompareController::class,
        'order' => Controller\OrderController::class,
        'payment' => Controller\PaymentController::class,
        'recommlist' => Controller\RecommListController::class,
        'rss' => Controller\RssController::class,
        'search' => Controller\SearchController::class,
        'start' => Controller\StartController::class,
        'thankyou' => Controller\ThankYouController::class,
        'wishlist' => Controller\WishListController::class,
        'wrapping' => Controller\WrappingController::class,
        'oxstart' => Controller\OxidStartController::class,
        'dynexportbase' => Controller\Admin\DynamicExportBaseController::class,
        'genimport_main' => Controller\Admin\GenericImportMain::class,
        'object_seo' => Controller\Admin\ObjectSeo::class,
        'shop_config' => Controller\Admin\ShopConfiguration::class,
        'clearcookies' => Controller\ClearCookiesController::class,
        'account_order' => Controller\AccountOrderController::class,
        'account_downloads' => Controller\AccountDownloadsController::class,
        'account_newsletter' => Controller\AccountNewsletterController::class,
        'account_password' => Controller\AccountPasswordController::class,
        'account_recommlist' => Controller\AccountRecommlistController::class,
        'account_reviewlist' => Controller\AccountReviewController::class,
        'contact' => Controller\ContactController::class,
        'credits' => Controller\CreditsController::class,
        'download' => Controller\DownloadController::class,
        'exceptionerror' => Controller\ExceptionErrorController::class,
        'forgotpwd' => Controller\ForgotPasswordController::class,
        'invite' => Controller\InviteController::class,
        'moredetails' => Controller\MoreDetailsController::class,
        'recommadd' => Controller\RecommendationAddController::class,
        'register' => Controller\RegisterController::class,
        'tpl' => Controller\TemplateController::class,
        'oxwactions' => Widget\Actions::class,
        'oxwcategorytree' => Widget\CategoryTree::class,
        'oxwinformation' => Widget\Information::class,
        'oxwrating' => Widget\Rating::class,
        'oxwservicemenu' => Widget\ServiceMenu::class,
        'oxwarticlebox' => Widget\ArticleBox::class,
        'oxwcookienote' => Widget\CookieNote::class,
        'oxwlanguagelist' => Widget\LanguageList::class,
        'oxwrecommendation' => Widget\Recommendation::class,
        'oxwarticledetails' => Widget\ArticleDetails::class,
        'oxwcurrencylist' => Widget\CurrencyList::class,
        'oxwmanufacturerlist' => Widget\ManufacturerList::class,
        'oxwreview' => Widget\Review::class,
        'oxwvendorlist' => Widget\VendorList::class,
        'oxwidget' => Widget\WidgetController::class,
        'oxwminibasket' => Widget\MiniBasket::class,
        'oxwservicelist' => Widget\ServiceList::class,
        'oxadminview' => Controller\Admin\AdminController::class,
        'oxadmindetails' => Controller\Admin\AdminDetailsController::class,
        'article_list' => Controller\Admin\ArticleList::class,
        'ajaxlistcomponent' => Controller\Admin\ListComponentAjax::class,
    ];

    /**
     * All available controller maps will be merged together like this: CE <- PE <- EE
     *
     * @return array Edition specific mapping of controller keys to classes
     */
    public function getControllerMap()
    {
        return $this->controllerMap;
    }
}
