services:
  _defaults:
    autowire: true

  OxidEsales\EshopCommunity\Internal\Framework\Authentication\Session\SessionUserProviderInterface:
    class: OxidEsales\EshopCommunity\Internal\Transition\Adapter\Authentication\SessionUserProvider
