services:
  _defaults:
    autowire: true

  OxidEsales\EshopCommunity\Internal\Transition\Adapter\Authentication\FrontendSessionUserProvider: ~
  OxidEsales\EshopCommunity\Internal\Transition\Adapter\Authentication\AdminSessionUserProvider: ~
