[{block name="pers_params__email_html_order_owner"}]
    [{if $oView->showPersParam($sPersParamKey) }]
	    <br />[{ $oView->getPersParamText($sPersParamKey) }] [{ $oView->getPersParamValue($sPersParamKey,$sPersParamValue) }]
    [{/if}]
[{/block}]
