parameters:
  oxid_esales.build_directory: '%env(OXID_BUILD_DIRECTORY)%'
  oxid_esales.shop_url: '%env(OXID_SHOP_BASE_URL)%'
  oxid_esales.log_level: '%env(OXID_LOG_LEVEL)%'
  oxid_esales.debug_mode: '%env(bool:OXID_DEBUG_MODE)%'
