parameters:
  oxid_esales.http.security_headers:
    X-Frame-Options: 'SAMEORIGIN'
    X-Content-Type-Options: 'nosniff'
    Referrer-Policy: 'strict-origin-when-cross-origin'
  oxid_esales.http.default_cache_control: 'no-store, no-cache, must-revalidate'
  oxid_esales.build_directory: '%env(OXID_BUILD_DIRECTORY)%'
  oxid_esales.shop_url: '%env(OXID_SHOP_BASE_URL)%'
  oxid_esales.log_level: '%env(OXID_LOG_LEVEL)%'
  oxid_esales.debug_mode: '%env(bool:OXID_DEBUG_MODE)%'
