imports:
    - { resource: Application/services.yaml }
    - { resource: Utility/services.yaml }
    - { resource: Logger/services.yaml }
    - { resource: Common/services.yaml }
    - { resource: Review/services.yaml }
    - { resource: Form/services.yaml }
    - { resource: Adapter/services.yaml }
    - { resource: Console/services.yaml }
    - { resource: Module/services.yaml }
    - { resource: Authentication/services.yaml }
