imports:
    - { resource: Container/services.yaml }
    - { resource: Framework/services.yaml }
    - { resource: Domain/services.yaml }
    - { resource: Transition/Adapter/services.yaml }
    - { resource: Transition/Smarty/services.yaml }
    - { resource: Transition/Utility/services.yaml }
