services:
  _defaults:
    autowire: true

  OxidEsales\EshopCommunity\Internal\Framework\Theme\View\ThemeViewServiceInterface:
    class: OxidEsales\EshopCommunity\Internal\Framework\Theme\View\ThemeViewService
    public: true
