services:
  _defaults:
    autowire: true

  OxidEsales\EshopCommunity\Internal\Setup\Validator\SetupInfrastructureValidatorInterface:
    class: OxidEsales\EshopCommunity\Internal\Setup\Validator\SetupInfrastructureValidator