services:
    _defaults:
        autowire: true

    OxidEsales\EshopCommunity\Internal\Setup\Database\SetupDbConnectionFactoryInterface:
        class: OxidEsales\EshopCommunity\Internal\Setup\Database\SetupDbConnectionFactory

    OxidEsales\EshopCommunity\Internal\Setup\Database\ViewsGeneratorFactoryInterface:
        class: OxidEsales\EshopCommunity\Internal\Setup\Database\ViewsGeneratorFactory

    OxidEsales\EshopCommunity\Internal\Setup\Database\ShopDbManagerInterface:
        class: OxidEsales\EshopCommunity\Internal\Setup\Database\ShopDbManager

    OxidEsales\EshopCommunity\Internal\Setup\Database\SetupDbConnectionValidatorInterface:
        class: OxidEsales\EshopCommunity\Internal\Setup\Database\SetupDbConnectionValidator
