services:
  _defaults:
    autowire: true

  OxidEsales\EshopCommunity\Internal\Framework\DIContainer\Service\ProjectYamlImportServiceInterface:
    class: OxidEsales\EshopCommunity\Internal\Framework\DIContainer\Service\ProjectYamlImportService
    public: true

  OxidEsales\EshopCommunity\Internal\Framework\DIContainer\Service\ContainerCacheInterface:
    class: OxidEsales\EshopCommunity\Internal\Framework\DIContainer\Service\FilesystemContainerCache
