<?php
/* 
THIS SCRIPT PROVIDES COMPATABILITY FOR SCRIPTS WRITTEN FOR WYSIWYGPRO 2.2.x
IF YOU DON'T NEED VERSION 2 COMPATABILITY THEN DON'T USE THIS SCRIPT!
*/

require_once(dirname(__FILE__).'/wysiwygPro.class.php');

?>