name: Manual run 7.0.x with Smarty

on:
  workflow_dispatch:
    inputs:
      limit:
        type: choice
        options:
          - 'no'
          - 'PHP8.0/MySQL5.7'
          - 'PHP8.0/MySQL8.0'
          - 'PHP8.1/MySQL5.7'
          - 'PHP8.1/MySQL8.0'
        default: 'PHP8.1/MySQL5.7'

jobs:
  build_testplan:
    runs-on: 'ubuntu-latest'
    outputs:
      testplan: '${{ steps.build.outputs.testplan }}'
    steps:
      - name: 'Build testplan'
        id: build
        run: |
          # Build testplan
          # shellcheck disable=SC2088
          case "${{ inputs.limit }}" in
            "no") LIMIT='';;
            "PHP8.0/MySQL5.7") LIMIT='~/defaults/php8.0_mysql5.7_only.yaml,' ;;
            "PHP8.0/MySQL8.0") LIMIT='~/defaults/php8.0_mysql8.0_only.yaml,' ;;
            "PHP8.1/MySQL5.7") LIMIT='~/defaults/php8.1_mysql5.7_only.yaml,' ;;
            "PHP8.1/MySQL8.0") LIMIT='~/defaults/php8.1_mysql8.0_only.yaml,' ;;
            *) echo "Illegal choice, fix the workflow"
              exit 1
              ;;
          esac
          # shellcheck disable=SC2088
          echo "testplan=~/defaults/7.0.x.yaml,${LIMIT}~/smarty_7.0.x.yaml" | tee -a "${GITHUB_OUTPUT}"

  smarty70x:
    needs: build_testplan
    uses: oxid-eSales/github-actions/.github/workflows/call-universal_test_workflow.yaml@v4
    with:
      testplan: ${{ needs.build_testplan.outputs.testplan }}
      runs_on: '"ubuntu-latest"'
      defaults: 'v4'
      plan_folder: '.github/oxid-esales'
    secrets:
      DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
      CACHE_ENDPOINT: ${{ secrets.CACHE_ENDPOINT }}
      CACHE_ACCESS_KEY: ${{ secrets.CACHE_ACCESS_KEY }}
      CACHE_SECRET_KEY: ${{ secrets.CACHE_SECRET_KEY }}
      enterprise_github_token: ${{ secrets.enterprise_github_token }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
