name: nightly_matrix_full_ce_71x
# Matrix workflow using re-usable github actions

on:
  schedule:
    - cron: '17 1 * * 1-5'

jobs:
  oxideshop_ce_71x_nightly:
    uses: oxid-eSales/github-actions/.github/workflows/call-universal_test_workflow.yml@v3
    with:
      testplan: 'tests/github_actions/defaults/7.1.x.yml,tests/github_actions/defaults/scheduled.yml,tests/github_actions/full_matrix_ce.yml'
      runs_on: '"ubuntu-latest"'
      defaults: 'v3'
    secrets:
      DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
      CACHE_ENDPOINT: ${{ secrets.CACHE_ENDPOINT }}
      CACHE_ACCESS_KEY: ${{ secrets.CACHE_ACCESS_KEY }}
      CACHE_SECRET_KEY: ${{ secrets.CACHE_SECRET_KEY }}
      enterprise_github_token: ${{ secrets.enterprise_github_token }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
