name: Auto trigger on PR to 8.0.x*
# Matrix workflow using re-usable github actions

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - b-8.0.x

jobs:
  oxideshop_ce_pull:
    uses: oxid-eSales/github-actions/.github/workflows/call-universal_test_workflow.yml@v3
    with:
      testplan: '~/full_matrix_ce.yml'
      runs_on: '"ubuntu-latest"'
      defaults: 'v3'
    secrets:
      DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
      CACHE_ENDPOINT: ${{ secrets.CACHE_ENDPOINT }}
      CACHE_ACCESS_KEY: ${{ secrets.CACHE_ACCESS_KEY }}
      CACHE_SECRET_KEY: ${{ secrets.CACHE_SECRET_KEY }}
      enterprise_github_token: ${{ secrets.enterprise_github_token }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
