name: Generate SBOM

on:
  push:
    branches:
      - b-7.6.x-sbom-automation-OXDEV-7300
  workflow_dispatch:

jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Generate SBOM
        id: sbom
        uses: OXID-eSales/github-actions/generate_sbom@v0
        with:
          spec_version: '1.4'

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v7
        with:
          name: sbom-oxideshop-ce
          path: ${{ steps.sbom.outputs.sbom_path }}
          if-no-files-found: error
