services:
    _defaults:
        autowire: true

    OxidEsales\EshopCommunity\Internal\Setup\Directory\DirectoryValidatorInterface:
        class: OxidEsales\EshopCommunity\Internal\Setup\Directory\DirectoryValidator
